### ISSUE TITLE
当结果存在 RRSIG 记录时，overture 不能正常转发结果

### ISSUE THREAD

**Issue by t123yh** [shawn1m/overture#100]
对请求的抓包如下：
[1.zip](https://github.com/shawn1m/overture/files/2288887/1.zip)

第一个请求（包 1-6）由我的路由器发起，可以看到 overture 先请求了国内 DNS，然后请求了国外 DNS；国外 DNS 返回了一个带 RRSIG 记录的结果，但最终 overture 返回给路由器的结果为空。第二个请求（包 7-12）由我的笔记本电脑发起，可以看到此时并没有请求 RRSIG 记录，overture 也返回了正常的结果。

**Comment by t123yh** [comment]
@shawn1m 那是否可以原样转发 RRSIG 记录？现在这样会导致部分有 RRSIG 的域名解析结果 NXDOMAIN。

**Comment by shawn1m** [comment]
能否提供一下 overture 的 verbose log，以及复现的手段（请求方式域名以及国外 DNS 服务器）。

**Comment by eldenchen** [comment]
遇到同样问题。
DNS: 1.1.1.1
查询域名: reviews.freebsd.org wiki.debian.org

**Comment by t123yh** [comment]
@shawn1m 这个问题不太好复现，因为好像只有我的路由器（OPNsense）的请求能让远端 DNS 返回 RRSIG。如果要复现的话可以试试把我的抓包中第一个请求包导出，找一个发包程序发给服务器（1.1.1.1）。

**Comment by eldenchen** [comment]
@t123yh unbound不能处理异常包大小的问题，换dnsmasq解决了
