### ISSUE TITLE
关于IPNetworkFile和DomainFile的理解

### ISSUE THREAD

**Issue by wang20150419** [shawn1m/overture#101]
关于配置文件的说明不仔细。

不知道我的理解对不对：

假定配置文件:
"IPNetworkFile": {
    "Primary": "./ip_network_sample",
  },
 "DomainFile": {
    "Alternative": "./domain_sample",
  },

IPNetworkFile： 指的是 由 Primary 解析某域名，解析的IP地址落在ip_network_sample范围内，
就直接返回解析结果，否则返回AlternativeDNS解析的结果。
DomainFile： 指的是域名在  domain_sample 文件里的，则由 AlternativeDNS 来解析。

是否OK？

**Comment by shawn1m** [comment]
是的，版本 1.4 之前是这样的，在文档中也有说明 Dispatch Process，你可以在源码库中选择旧版本的 tag 中确认。
