### ISSUE TITLE
TTL缓存问题-

### ISSUE THREAD

**Issue by feika** [shawn1m/overture#102]
修改了TTL的时间到一个很大的值（一周），dig的时候也会显示这个值，但是事实上过了几分钟后再次dig同一个网站，又会重新向上游dns服务器重新查询， dns cachesize也已经改到了1500

**Comment by shawn1m** [comment]
目前的策略存进 cache 的 message 时效按照原有 ttl，只自定义 ttl 只影响返回给客户端的 message。

**Comment by shawn1m** [comment]
Try version v1.5-rc1.

**Comment by lix5027** [comment]
我用rc3版本好像ttl缓存时间不生效?测试的时候设置为MinimumTTL: 10
结果就算过去1分钟,再查询结果,依然是给的cache数据,不从上游dns从新更新

而且原本数据是280秒超时,我等超过300秒了,他也不自动刷新,

貌似只要开了cache,那么同一条记录永久都不去从上游dns刷新,超时 设置cache的ttl,和本身ttl都没用
