### ISSUE TITLE
Suggestion: Option to perform remote DNS lookups over SOCKS5 proxy

### ISSUE THREAD

**Issue by phantomcraft** [shawn1m/overture#103]
If a SOCKS5 proxy has builtin DNS resolution, instead of passing a remote DNS server (8.8.8.8, 1.1.1.1 and others), ask the proxy for resolve domains directly with its own DNS.

Just like Curl does with --socks5h: https://curl.haxx.se/libcurl/c/CURLOPT_SOCKS_PROXY.html

> "or socks5h:// (the last one to enable socks5 and asking the proxy to do the resolving, also known as CURLPROXY_SOCKS5_HOSTNAME type)"

It could be useful with Tor.

**Comment by shawn1m** [comment]
The socks5 is implemented by Go standard library and I do not want to build a new one by now.
