### ISSUE TITLE
DNSPod Fail

### ISSUE THREAD

**Issue by kaniwow** [shawn1m/overture#107]
在运行的时候发现墙外记录都能找到
但是墙内就凉了XD

我试着使用了
`dig www.baidu.com @127.0.0.1 -p 8053 `
的方式进行查询（我给的端口在8053，因为是作为DNSmasq的上游）
然后反馈是

> ; <<>> DiG 9.11.3-1ubuntu1.3-Ubuntu <<>> www.baidu.com @127.0.0.1 -p 8053
;; global options: +cmd
;; connection timed out; no servers could be reached

大致这样。
由于是Ubuntu18.04，我只对python3.6进行了apt install，于是我是用screen在后台挂着Overture的。

**Comment by kaniwow** [comment]
当我回头去screen 中查看的时候出现了类似这样的错误提示

> WARN[0080] DNSPod Fail: read udp 172.19.51.126:38202->119.29.29.29:53: i/o timeout
WARN[0085] DNSPod Fail: read udp 172.19.51.126:57058->119.29.29.29:53: i/o timeout
WARN[0090] DNSPod Fail: read udp 172.19.51.126:42885->119.29.29.29:53: i/o timeout
WARN[0096] DNSPod Fail: read udp 172.19.51.126:50712->119.29.29.29:53: i/o timeout
WARN[0101] DNSPod Fail: read udp 172.19.51.126:46151->119.29.29.29:53: i/o timeout
WARN[0106] DNSPod Fail: read udp 172.19.51.126:36140->119.29.29.29:53: i/o timeout
WARN[2931] DNSPod Fail: read udp 172.19.51.126:33076->119.29.29.29:53: i/o timeout
WARN[2936] DNSPod Fail: read udp 172.19.51.126:54772->119.29.29.29:53: i/o timeout
WARN[2941] DNSPod Fail: read udp 172.19.51.126:46273->119.29.29.29:53: i/o timeout

**Comment by shawn1m** [comment]
应该是你那里到 119.29.29.29 无法连接吧，无法复现。

**Comment by flashbenny** [comment]
同样的问题. 每次i/o timeout后overture就退出了. 尝试在config里把Timeout数值调大也不行. 基本就是运行10分钟后退出
