### ISSUE TITLE
Dnspod 无法解析，分析过程

### ISSUE THREAD

**Issue by ryanlycch** [shawn1m/overture#108]
把Primary DNS设置为119.29.29.29后无法解析，分析如下：
1. 通过119.29.29.29 udp解析时，必须要设置ECS IP才可以，不然无法解析
2. 设置ECS IP后，overture还是无法解析，但dig正常。抓包后发现两者的请求包唯一区别在于Addition records中subnet和cookie的封装顺序不一样。dig是subnet在前，cookie在后，overture是反过来cookie在前了。
3. 解析国外域名时Addition records中没有附加cookie信息

![dnspod](https://user-images.githubusercontent.com/21031109/47764042-53c4a400-dcfe-11e8-8883-6a0aa0173b2c.png)

**Comment by ryanlycch** [comment]
Overture不支持设置这个选项吧，另外，我看源代码master/core/common/edns.go中的42行
`o.Option = append(o.Option, es)`，是把subnet选项追加到最后的，不知道能不能改成插入到最前面，这样即使有cookie也可以解析成功的。可惜不会程序

**Comment by shawn1m** [comment]
可以考虑调换一下顺序，近期会做。

**Comment by shawn1m** [comment]
Try version v1.5-rc1, you can define "NoCookie" in "EDNSClientSubnet".
