### ISSUE TITLE
read udp i/o timeout

### ISSUE THREAD

**Issue by qwwind** [shawn1m/overture#112]
base 广东佛山，新拉的一条电信宽带，PrimaryDNS，添加了3条记录，screen 运行的监控日志，发现大量的timeout，连接3个dns 服务器都有。将dns 设置到电脑使用，可以正常解析，正常上网。在机器上dig 测试，可以解析

WARN[0158] dianxin2 Fail: read udp 172.17.5.2:44935->202.96.128.166:53: i/o timeout
WARN[0170] DNSPod Fail: read udp 172.17.5.2:54418->119.29.29.29:53: i/o timeout
WARN[0177] dianxin1 Fail: read udp 172.17.5.2:38657->202.96.134.133:53: i/o timeout
WARN[0195] dianxin1 Fail: dns: overflow unpacking uint32
WARN[0201] dianxin1 Fail: read udp 172.17.5.2:40783->202.96.134.133:53: i/o timeout
WARN[0210] dianxin1 Fail: read udp 172.17.5.2:43731->202.96.134.133:53: i/o timeout
WARN[0217] dianxin1 Fail: read udp 172.17.5.2:43102->202.96.134.133:53: i/o timeout
WARN[0235] DNSPod Fail: read udp 172.17.5.2:43312->119.29.29.29:53: i/o timeout
WARN[0236] DNSPod Fail: read udp 172.17.5.2:48480->119.29.29.29:53: i/o timeout
WARN[0240] dianxin1 Fail: read udp 172.17.5.2:36494->202.96.134.133:53: i/o timeout
WARN[0240] dianxin1 Fail: read udp 172.17.5.2:55435->202.96.134.133:53: i/o timeout
WARN[0247] DNSPod Fail: read udp 172.17.5.2:58041->119.29.29.29:53: i/o timeout
WARN[0247] dianxin1 Fail: read udp 172.17.5.2:50134->202.96.134.133:53: i/o timeout
WARN[0247] dianxin2 Fail: read udp 172.17.5.2:40455->202.96.128.166:53: i/o timeout
WARN[0249] dianxin1 Fail: read udp 172.17.5.2:46603->202.96.134.133:53: i/o timeout
WARN[0251] DNSPod Fail: read udp 172.17.5.2:56239->119.29.29.29:53: i/o timeout
WARN[0251] dianxin1 Fail: read udp 172.17.5.2:41282->202.96.134.133:53: i/o timeout
WARN[0263] DNSPod Fail: read udp 172.17.5.2:35677->119.29.29.29:53: i/o timeout
WARN[0280] dianxin1 Fail: read udp 172.17.5.2:41238->202.96.134.133:53: i/o timeout
WARN[0291] dianxin1 Fail: read udp 172.17.5.2:45396->202.96.134.133:53: i/o timeout
WARN[0292] dianxin1 Fail: read udp 172.17.5.2:37139->202.96.134.133:53: i/o timeout
WARN[0318] dianxin2 Fail: read udp 172.17.5.2:40684->202.96.128.166:53: i/o timeout
WARN[0318] DNSPod Fail: read udp 172.17.5.2:50508->119.29.29.29:53: i/o timeout
WARN[0318] dianxin1 Fail: read udp 172.17.5.2:45649->202.96.134.133:53: i/o timeout
WARN[0319] dianxin1 Fail: read udp 172.17.5.2:48159->202.96.134.133:53: i/o timeout
WARN[0328] dianxin1 Fail: read udp 172.17.5.2:47758->202.96.134.133:53: i/o timeout
WARN[0328] dianxin2 Fail: read udp 172.17.5.2:52673->202.96.128.166:53: i/o timeout
WARN[0359] dianxin1 Fail: read udp 172.17.5.2:53622->202.96.134.133:53: i/o timeout
WARN[0365] dianxin1 Fail: read udp 172.17.5.2:60303->202.96.134.133:53: i/o timeout
WARN[0373] dianxin2 Fail: read udp 172.17.5.2:43122->202.96.128.166:53: i/o timeout
WARN[0373] dianxin1 Fail: read udp 172.17.5.2:45944->202.96.134.133:53: i/o timeout
WARN[0400] dianxin1 Fail: read udp 172.17.5.2:50642->202.96.134.133:53: i/o timeout
WARN[0401] dianxin2 Fail: read udp 172.17.5.2:58538->202.96.128.166:53: i/o timeout
WARN[0401] dianxin1 Fail: read udp 172.17.5.2:37102->202.96.134.133:53: i/o timeout
WARN[0414] dianxin1 Fail: read udp 172.17.5.2:45382->202.96.134.133:53: i/o timeout
WARN[0432] dianxin2 Fail: read udp 172.17.5.2:47907->202.96.128.166:53: i/o timeout
WARN[0437] dianxin1 Fail: read udp 172.17.5.2:54074->202.96.134.133:53: i/o timeout
^[[AWARN[0454] dianxin1 Fail: read udp 172.17.5.2:48914->202.96.134.133:53: i/o timeout

**Comment by shawn1m** [comment]
这个应该是具体的网络环境问题吧，无法复现也没有其他用户遇到。

**Comment by vissible** [comment]
同样遇到，
`
time="2019-02-01T22:04:49+08:00" level=warning msg="DNSPod Fail: read udp 192.168.0.11:23583->119.28.28.28:53: i/o timeout"
time="2019-02-01T22:04:49+08:00" level=warning msg="DNSPod Fail: read udp 192.168.0.11:22501->119.28.28.28:53: i/o timeout"
time="2019-02-01T22:04:49+08:00" level=warning msg="DNSPod Fail: read udp 192.168.0.11:53282->119.28.28.28:53: i/o timeout"
time="2019-02-01T22:04:50+08:00" level=warning msg="DNSPod Fail: read udp 192.168.0.11:60346->119.28.28.28:53: i/o timeout"
time="2019-02-01T22:04:52+08:00" level=warning msg="DNSPod Fail: read udp 192.168.0.11:10769->119.28.28.28:53: i/o timeout"
time="2019-02-01T22:04:54+08:00" level=warning msg="DNSPod Fail: read udp 192.168.0.11:39950->119.28.28.28:53: i/o timeout"
`

**Comment by onecat** [comment]
广州电信同样出现问题，无论udp还是tcp都出现大量time out，用的Overture v1.5-rc3

**Comment by BirkhoffLee** [comment]
江苏电信一样问题

**Comment by Jasper-1024** [comment]
v1.5-rc3 版本出现,换用最新版 v1.5 无问题,仅供参考

**Comment by yiguihai** [comment]
INFO[2019-07-21 17:07:45] Overture v1.6-rc3
INFO[2019-07-21 17:07:45] If you need any help, please visit the project repository: https://github.com/shawn1m/overture
INFO[2019-07-21 17:07:45] Domain TTL file /data/local/tmp/shadowsocks/overture/domain_ttl_sample has been loaded with 1 records
INFO[2019-07-21 17:07:45] Domain file /data/local/tmp/shadowsocks/overture/domain_primary_sample has been loaded with 1 records (regex-list)
INFO[2019-07-21 17:07:45] Domain file /data/local/tmp/shadowsocks/overture/domain_alternative_sample has been loaded with 1 records (regex-list)
INFO[2019-07-21 17:07:45] IP network file /data/local/tmp/shadowsocks/overture/ip_network_primary_sample has been successfully loaded
INFO[2019-07-21 17:07:45] IP network file /data/local/tmp/shadowsocks/overture/ip_network_alternative_sample has been successfully loaded
INFO[2019-07-21 17:07:45] Minimum TTL is disabled
INFO[2019-07-21 17:07:45] Cache is disabled
DEBU[2019-07-21 17:07:45] Load hosts took 833ns
INFO[2019-07-21 17:07:45] Hosts file has been loaded successfully
INFO[2019-07-21 17:07:45] Overture is listening on :1053
DEBU[2019-07-21 17:07:50] Question from 127.0.0.1: ;music.163.com.      IN                                  A
DEBU[2019-07-21 17:07:50] Domain Primary match fail
DEBU[2019-07-21 17:07:50] Domain Alternative match fail
DEBU[2019-07-21 17:07:52] DNSPod Fail: read udp 100.99.78.205:41097->119.29.29.29:53: i/o timeout
DEBU[2019-07-21 17:07:52] Primary DNS return nil, finally use alternative DNS
DEBU[2019-07-21 17:07:52] Answer from OpenDNS: music.163.com.   29      IN                                 103.126.92.132
DEBU[2019-07-21 17:07:52] Answer from OpenDNS: music.163.com.   29      IN                                 103.126.92.133
