### ISSUE TITLE
Support softfloat for MIPS MIPSLE MIPS64 MIPS64LE

### ISSUE THREAD

**Issue by IrineBrunner** [shawn1m/overture#113]
> For mips users, please assure the kernel FPU emulation is enabled, check #32 #26 golang/go#18880 for details.

Golang now support both hardfloat and softfloat. So we can disable FPU emulation and simply set environment variables `GOMIPS` `GOMIPS64`

> GOMIPS
> For GOARCH=mips{,le}, whether to use floating point instructions.
> 	Valid values are hardfloat (default), softfloat.
> GOMIPS64
> 	For GOARCH=mips64{,le}, whether to use floating point instructions.
> 	Valid values are hardfloat (default), softfloat.

[Reference](https://golang.org/cmd/go/#hdr-Environment_variables)

**Comment by shawn1m** [comment]
See #86.
README is updated, thanks!
