### ISSUE TITLE
build的时候有错误提示

### ISSUE THREAD

**Issue by lix5027** [shawn1m/overture#114]
[root@localhost overture]# ./build.py -build
github.com/shawn1m/overture/core/outbound
# github.com/shawn1m/overture/core/outbound
/root/go/src/github.com/shawn1m/overture/core/outbound/client.go:97:13: undefined: dns.ErrTruncated
Traceback (most recent call last):
  File "./build.py", line 65, in <module>
    go_build_zip()
  File "./build.py", line 25, in go_build_zip
    subprocess.check_call("go get -v github.com/shawn1m/overture/main", shell=True)
  File "/usr/lib64/python3.4/subprocess.py", line 558, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'go get -v github.com/shawn1m/overture/main' returned non-zero exit status 2

提示执行
go get -v github.com/shawn1m/overture/main
的时候 有个dns.errTruncated没定义?
/root/go/src/github.com/shawn1m/overture/core/outbound/client.go:97:13: undefined: dns.ErrTruncated

**Comment by lix5027** [comment]
确实是,对照的改一下可以继续了
不过又卡在go版本上了貌似?
[root@localhost overture]# ./build.py -build
# command-line-arguments
main/main.go:57:17: not enough arguments in call to core.InitServer
        have (string)
        want (string, bool)
linux amd64  failed.
[root@localhost overture]#

**Comment by shawn1m** [comment]
core.InitServer 你应该修改成参数为 (string, bool) 了，原来是 (string)，语言问题 google 一下吧
