### ISSUE TITLE
一个小众群体判断污染的方法

### ISSUE THREAD

**Issue by lix5027** [shawn1m/overture#115]
在教育网下,我有一个判断污染的办法.
就是把地址解析到1.2.3.4上.
比如 nslookup www.google.com 1.2.3.4
如果是被污染的.则马上会反馈投毒地址.
如果正常地址,则查询超时.

我想能不能在程序里加一个防污染测试的配置,用来收集投毒地址,和污染域名.可以追加写入txt文件,(DomainFile Alternative.txt, IP Alternative.txt),从而在下次查询的时候会直接根据txt策略来做解析.
并且也方便分享最新的投毒地址和真实污染域名池,本来想自己做,结果不是太会go的编程,而且第一次尝试build的时候以失败告终..希望作者可以帮忙增加这样的设置
#########################################################
以下测试防污染只在教育网下成功:

[root@localhost overture]# nslookup www.google.com 1.2.3.4
Server:         1.2.3.4
Address:        1.2.3.4#53

Non-authoritative answer:
Name:   www.google.com
Address: 69.171.230.18

正常地址则超时无响应.(测试的ip不一定是1.2.3.4,任意一个没开53端口的部分国外ip都可以做测试)

**Comment by shawn1m** [comment]
不打算支持，overture 现在与未来主要侧重于 dns 的动态分流，对非标准协议实现动力不大。

**Comment by import-yuefeng** [comment]
我认为是一个非常好的办法，用于优化 DNS 的查询效果。我会尝试在 smartDNS 中detecter 增加该方式。 @lix5027
