### ISSUE TITLE
Freebsd 版本崩溃

### ISSUE THREAD

**Issue by echowings** [shawn1m/overture#119]

**Comment by echowings** [comment]
overture -v
INFO[0000] Overture v1.5-rc1
INFO[0000] If you need any help, please visit the project repository: https://github.com/shawn1m/overture
INFO[0000] Load domain /usr/local/etc/overture/domain_primary_sample successful with 1 records
INFO[0000] Load domain /usr/local/etc/overture/gfw_all_domain.txt successful with 7898 records
INFO[0000] Load /usr/local/etc/overture/china_ip_list.txt successful
INFO[0000] Load /usr/local/etc/overture/ip_network_alternative_sample successful
INFO[0000] Minimum TTL is disabled
INFO[0000] Cache is disabled
DEBU[0000] Load hosts took 10.58µs
INFO[0000] Load hosts file successful
INFO[0000] Start overture on :53
DEBU[0004] Question from 10.32.201.163: ;c-5uwzmx78pmca09x24kx2eiuihwv-ilagabmux2ekwu.g00.gamepedia.com.	IN	 A
DEBU[0004] Domain primary match fail
DEBU[0004] Domain alternative match fail
DEBU[0004] Question from 10.32.201.163: ;www.sdad.guru.	IN	 A
DEBU[0004] Domain primary match fail
DEBU[0004] Domain alternative match fail
DEBU[0004] Answer from DNSPod: c-5uwzmx78pmca09x24kx2eiuihwv-ilagabmux2ekwu.g00.gamepedia.com.	300	IN	CNAME	gamepedia-wildcard.inscname.net.
DEBU[0004] Answer from DNSPod: gamepedia-wildcard.inscname.net.	391	IN	CNAME	ins-065.inscname.net.
DEBU[0004] Answer from DNSPod: ins-065.inscname.net.	3391	IN	CNAME	SG01SL04-HKG01.inscname.net.
DEBU[0004] Answer from DNSPod: sg01sl04-hkg01.inscname.net.	14	IN	A103.243.14.80
DEBU[0004] Try to match response ip address with IP network
DEBU[0004] IP network match failed, finally use alternative DNS
DEBU[0004] Try to match response ip address with IP network
DEBU[0004] IP network match failed, finally use alternative DNS
DEBU[0004] Try to match response ip address with IP network
DEBU[0004] IP network match failed, finally use alternative DNS
DEBU[0004] Try to match response ip address with IP network
DEBU[0004] IP network match failed, finally use alternative DNS
DEBU[0004] Answer from OpenDNS: c-5uwzmx78pmca09x24kx2eiuihwv-ilagabmux2ekwu.g00.gamepedia.com.	300	IN	CNAME	gamepedia-wildcard.inscname.net.
DEBU[0004] Answer from OpenDNS: gamepedia-wildcard.inscname.net.	515	IN	CNAME	ins-065.inscname.net.
DEBU[0004] Answer from OpenDNS: ins-065.inscname.net.	3515	IN	CNAME	SG01SL04-HKG01.inscname.net.
DEBU[0004] Answer from OpenDNS: SG01SL04-HKG01.inscname.net.	30	IN	A103.243.14.80
DEBU[0005] Question from 10.32.201.163: ;c-5uwzmx78pmca09x24eeex2eowwotmbioamzdqkmax2ekwu.g00.gamepedia.com.	IN	 A
DEBU[0005] Domain primary match fail
DEBU[0005] Domain alternative match fail
DEBU[0005] Answer from DNSPod: c-5uwzmx78pmca09x24eeex2eowwotmbioamzdqkmax2ekwu.g00.gamepedia.com.	283	IN	CNAME	gamepedia-wildcard.inscname.net.
DEBU[0005] Answer from DNSPod: gamepedia-wildcard.inscname.net.	390	IN	CNAME	ins-065.inscname.net.
DEBU[0005] Answer from DNSPod: ins-065.inscname.net.	3390	IN	CNAME	SG01SL04-HKG01.inscname.net.
DEBU[0005] Answer from DNSPod: sg01sl04-hkg01.inscname.net.	13	IN	A103.243.14.80
DEBU[0005] Try to match response ip address with IP network
DEBU[0005] IP network match failed, finally use alternative DNS
DEBU[0005] Try to match response ip address with IP network
DEBU[0005] IP network match failed, finally use alternative DNS
DEBU[0005] Try to match response ip address with IP network
DEBU[0005] IP network match failed, finally use alternative DNS
DEBU[0005] Try to match response ip address with IP network
DEBU[0005] IP network match failed, finally use alternative DNS
DEBU[0005] Answer from OpenDNS: c-5uwzmx78pmca09x24eeex2eowwotmbioamzdqkmax2ekwu.g00.gamepedia.com.	300	IN	CNAME	gamepedia-wildcard.inscname.net.
DEBU[0005] Answer from OpenDNS: gamepedia-wildcard.inscname.net.	515	IN	CNAME	ins-065.inscname.net.
DEBU[0005] Answer from OpenDNS: ins-065.inscname.net.	3515	IN	CNAME	SG01SL04-HKG01.inscname.net.
DEBU[0005] Answer from OpenDNS: SG01SL04-HKG01.inscname.net.	15	IN	A103.243.14.80
WARN[0006] DNSPod Fail: read tcp 10.32.1.6:32529->119.29.29.29:53: i/o timeout
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5bb216]

goroutine 35 [running]:
github.com/miekg/dns.(*Msg).PackBuffer(0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0xc4202ba230, 0xc4202b8038, 0xc420305c08)
	/home/travis/gopath/src/github.com/miekg/dns/msg.go:757 +0x26
github.com/miekg/dns.(*Msg).Pack(0x0, 0x1, 0x4, 0xc4202ea0c0, 0xd, 0x0)
	/home/travis/gopath/src/github.com/miekg/dns/msg.go:750 +0x3c
github.com/miekg/dns.(*response).WriteMsg(0xc4202b2180, 0x0, 0x1, 0xc4202f00b0)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:770 +0x4c
github.com/shawn1m/overture/core/inbound.(*Server).ServeDNS(0xc42009a6c0, 0x6edf60, 0xc4202b2180, 0xc4202e02d0)
	/home/travis/gopath/src/github.com/shawn1m/overture/core/inbound/server.go:65 +0x26e
github.com/miekg/dns.(*ServeMux).ServeDNS(0xc420072720, 0x6edf60, 0xc4202b2180, 0xc4202e02d0)
	/home/travis/gopath/src/github.com/miekg/dns/serve_mux.go:128 +0x61
github.com/miekg/dns.(*Server).serveDNS(0xc420130200, 0xc4202b2180)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:688 +0x2cb
github.com/miekg/dns.(*Server).serve(0xc420130200, 0xc4202b2180)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:573 +0x2d9
github.com/miekg/dns.(*Server).worker(0xc420130200, 0xc4202b2180)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:244 +0x4d
created by github.com/miekg/dns.(*Server).spawnWorker
	/home/travis/gopath/src/github.com/miekg/dns/server.go:284 +0x85


uname -a
FreeBSD templatefreebsd12 12.0-RELEASE FreeBSD 12.0-RELEASE r341666 GENERIC  amd64

**Comment by shawn1m** [comment]
Same as #118, try v1.5-rc2.
