### ISSUE TITLE
IPv6 查询结果返回缺少或不正确

### ISSUE THREAD

**Issue by pkron** [shawn1m/overture#121]
正在使用的版本：v1.5-rc1 (Ubuntu-x64)

你的使用场景是：查询 www.qq.com 域名

看到的不正常是：返回的 IPv6 地址为“空白”或“海外地址”

你期待看到的是：按配置文件 ip_network_primary 正确返回地址

附上的配置文件： [Report.zip](https://github.com/shawn1m/overture/files/2698437/Report.zip)

出错时软件输出：

C:\Users\Administrator>nslookup www.qq.com 192.168.50.100
伺服器:  UnKnown
Address:  192.168.50.100

未經授權的回答:
名稱:    https.qq.com
Address:  183.3.226.35
Aliases:  www.qq.com

C:\Users\Administrator>nslookup www.qq.com 192.168.50.100
伺服器:  UnKnown
Address:  192.168.50.100

未經授權的回答:
名稱:    e6156.dscf.akamaiedge.net
Addresses:  2600:1409:a:79b::180c
          2600:1409:a:786::180c
          183.3.226.35
Aliases:  www.qq.com
          news.qq.com.edgekey.net

**Comment by kiolygenius** [comment]
我也遇到了，在 ip_network_primary 里面也同时配置了 ipv4 和 ipv6 的 中国网段。但是网易、腾讯的首页域名返回的都是 alternative 的海外 dns 返回的 AAAA 记录，A 记录倒是正确的。
版本是 1.4

**Comment by kiolygenius** [comment]
看了下代码，
core/outbound/dispatcher.go, Line 145
应该写错了。

**Comment by kiolygenius** [comment]
以下是 IPv4 的解析过程，正确
"Question from 119.3.0.118: ;ulogs.umeng.com.	IN	 A"
"Domain primary match fail"
"Domain alternative match fail"
"Answer from DNSPod: ulogs.umeng.com.	300	IN	CNAME	et2-na61-na62.wagbridge.alibaba.tanx.com."
"Answer from DNSPod: et2-na61-na62.wagbridge.alibaba.tanx.com.	300	IN	CNAME	et2-na61-na62.wagbridge.alibaba.tanx.com.gds.alibabadns.com."
"Answer from DNSPod: et2-na61-na62.wagbridge.alibaba.tanx.com.gds.alibabadns.com.	120	IN	A	203.119.214.125"
"Try to match response ip address with IP network"
"IP network match failed, finally use alternative DNS"
"Try to match response ip address with IP network"
"IP network match failed, finally use alternative DNS"
"Try to match response ip address with IP network"
"Matched: IP network primary 203.119.214.125 203.119.128.0/17"
"Finally use primary DNS"
"Cached: ulogs.umeng.com. 1 119.3.0.118"

以下是 IPv6 的解析过程，错误
"Question from 110.83.49.77: ;www.189.cn.	IN	 AAAA"
"Domain primary match fail"
"Domain alternative match fail"
"Answer from DNSPod: www.189.cn.	28739	IN	CNAME	www.189.chinacache.net."
"Answer from DNSPod: www.189.chinacache.net.	7139	IN	CNAME	189.cn.v4.ccgslb.com.cn."
"Answer from DNSPod: 189.cn.v4.ccgslb.com.cn.	59	IN	CNAME	189.cn.v6.lxsvc.cn."
"Answer from DNSPod: 189.cn.v6.lxsvc.cn.	59	IN	CNAME	public-ipv6-chn.tel.lxsvc.cn."
"Try to match response ip address with IP network"
"IP network match failed, finally use alternative DNS"
"Try to match response ip address with IP network"
"IP network match failed, finally use alternative DNS"
"Try to match response ip address with IP network"
"IP network match failed, finally use alternative DNS"
"Try to match response ip address with IP network"
"IP network match failed, finally use alternative DNS"
"Answer from DNSPod 2: www.189.cn.	28800	IN	CNAME	www.189.chinacache.net."
"Answer from DNSPod 2: www.189.chinacache.net.	7200	IN	CNAME	189.cn.v4.ccgslb.com.cn."
"Answer from DNSPod 2: 189.cn.v4.ccgslb.com.cn.	120	IN	CNAME	189.cn.v6.lxsvc.cn."
"Answer from DNSPod 2: 189.cn.v6.lxsvc.cn.	120	IN	CNAME	public-ipv6-chn.tel.lxsvc.cn."
"Answer from DNSPod 2: public-ipv6-chn.tel.lxsvc.cn.	120	IN	AAAA	240e:cf:8001::2"
"Answer from DNSPod 2: public-ipv6-chn.tel.lxsvc.cn.	120	IN	AAAA	240e:e1:f000:1::11"
"Answer from DNSPod 2: public-ipv6-chn.tel.lxsvc.cn.	120	IN	AAAA	240e:bf:c800:e000::11"
"Answer from DNSPod 2: public-ipv6-chn.tel.lxsvc.cn.	120	IN	AAAA	240e:c1:5ff0:4::11"
"Answer from DNSPod 2: public-ipv6-chn.tel.lxsvc.cn.	120	IN	AAAA	240e:c9:4000:200::3"
"Answer from DNSPod 2: public-ipv6-chn.tel.lxsvc.cn.	120	IN	AAAA	240e:c9:4000:200::9"
"Answer from DNSCrypt v2: www.189.cn.	27137	IN	CNAME	www.189.chinacache.net."
"Answer from DNSCrypt v2: www.189.chinacache.net.	5537	IN	CNAME	189.cn.v4.ccgslb.com.cn."
"Answer from DNSCrypt v2: 189.cn.v4.ccgslb.com.cn.	120	IN	CNAME	189.cn.v6.lxsvc.cn."
"Answer from DNSCrypt v2: 189.cn.v6.lxsvc.cn.	120	IN	CNAME	public-ipv6-cnc.cnc.lxsvc.cn."
"Answer from DNSCrypt v2: public-ipv6-cnc.cnc.lxsvc.cn.	120	IN	AAAA	2408:871a:6010::11"
"Answer from DNSCrypt v2: public-ipv6-cnc.cnc.lxsvc.cn.	120	IN	AAAA	2408:872b:e01:1::2"
"Answer from DNSCrypt v2: public-ipv6-cnc.cnc.lxsvc.cn.	120	IN	AAAA	2408:871a:1101::1000:10"
"Answer from DNSCrypt v2: public-ipv6-cnc.cnc.lxsvc.cn.	120	IN	AAAA	2408:871a:8810:100::11"
"Cached: www.189.cn. 28 "

IP_Network_Primary 里面是有中国大陆的IP网段的 ( 240e::/20 )

**Comment by shawn1m** [comment]
Fix in v1.5-rc2.
