### ISSUE TITLE
自动退出的问题 (ver:1.5RC3)

### ISSUE THREAD

**Issue by flashbenny** [shawn1m/overture#125]
当前版本的overture (1.5RC3), 在所有的primary DNS 出现i/o timeout的情况下, 就会自动退出. 即便使用supervisor也没什么效果, 显示的还是EXITED. 测试了在只用DNSPod的情况下, 最多坚持了30分钟, 加上本地DNS坚持了不到4个小时, 又加了一个114的DNS, 目前为止运行时间超过3天了. log里全是i/o timeout. 
是不是可以考虑在读取i/o timeout时候, 让overture先暂停解析, 一旦接到回应则继续运行? 

time="2019-01-08T10:15:38+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:38693->202.102.128.68:53: i/o timeout"
time="2019-01-08T10:15:57+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:53952->202.102.128.68:53: i/o timeout"
time="2019-01-08T10:29:24+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:50189->202.102.128.68:53: i/o timeout"
time="2019-01-08T10:29:30+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:38488->202.102.128.68:53: i/o timeout"
time="2019-01-08T10:40:02+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:54884->202.102.128.68:53: i/o timeout"
time="2019-01-08T12:30:00+08:00" level=warning msg="114 Fail: read udp 10.5.10.17:51738->114.114.114.114:53: i/o timeout"
time="2019-01-08T12:50:04+08:00" level=warning msg="DNSPod Fail: read udp 10.5.10.17:43131->119.29.29.29:53: i/o timeout"
time="2019-01-08T12:54:05+08:00" level=warning msg="DNSPod Fail: read udp 10.5.10.17:36935->119.29.29.29:53: i/o timeout"
time="2019-01-08T12:54:05+08:00" level=warning msg="DNSPod Fail: read udp 10.5.10.17:46868->119.29.29.29:53: i/o timeout"
time="2019-01-08T12:54:05+08:00" level=warning msg="DNSPod Fail: read udp 10.5.10.17:60265->119.29.29.29:53: i/o timeout"
time="2019-01-08T12:54:05+08:00" level=warning msg="DNSPod Fail: read udp 10.5.10.17:34557->119.29.29.29:53: i/o timeout"
time="2019-01-08T13:08:48+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:44971->202.102.128.68:53: i/o timeout"
time="2019-01-08T13:09:02+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:34208->202.102.128.68:53: i/o timeout"
time="2019-01-08T13:09:04+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:47984->202.102.128.68:53: i/o timeout"
time="2019-01-08T13:09:07+08:00" level=warning msg="DNSPod Fail: read udp 10.5.10.17:52278->119.29.29.29:53: i/o timeout"
time="2019-01-08T15:07:34+08:00" level=warning msg="114 Fail: read udp 10.5.10.17:37482->114.114.114.114:53: i/o timeout"
time="2019-01-08T15:42:13+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:46009->202.102.128.68:53: i/o timeout"
time="2019-01-08T15:42:16+08:00" level=warning msg="114 Fail: read udp 10.5.10.17:47756->114.114.114.114:53: i/o timeout"
time="2019-01-08T15:42:16+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:47661->202.102.128.68:53: i/o timeout"
time="2019-01-08T15:42:21+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:55945->202.102.128.68:53: i/o timeout"
time="2019-01-08T15:42:21+08:00" level=warning msg="114 Fail: read udp 10.5.10.17:44411->114.114.114.114:53: i/o timeout"
time="2019-01-08T15:51:26+08:00" level=warning msg="DNSPod Fail: read udp 10.5.10.17:36195->119.29.29.29:53: i/o timeout"
time="2019-01-08T16:49:30+08:00" level=warning msg="114 Fail: read udp 10.5.10.17:48250->114.114.114.114:53: i/o timeout"
time="2019-01-08T21:56:19+08:00" level=warning msg="DNSPod Fail: read udp 10.5.10.17:52257->119.29.29.29:53: i/o timeout"
time="2019-01-09T01:40:24+08:00" level=warning msg="DNSPod Fail: read udp 10.5.10.17:51117->119.29.29.29:53: i/o timeout"
time="2019-01-09T09:30:37+08:00" level=warning msg="114 Fail: read udp 10.5.10.17:56524->114.114.114.114:53: i/o timeout"
time="2019-01-09T10:30:21+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:45881->202.102.128.68:53: i/o timeout"
time="2019-01-09T11:08:40+08:00" level=warning msg="DNSPod Fail: read udp 10.5.10.17:50425->119.29.29.29:53: i/o timeout"
time="2019-01-09T11:12:12+08:00" level=warning msg="114 Fail: read udp 10.5.10.17:43637->114.114.114.114:53: i/o timeout"
time="2019-01-09T11:12:59+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:59389->202.102.128.68:53: i/o timeout"
time="2019-01-09T11:58:26+08:00" level=warning msg="DNSPod Fail: read udp 10.5.10.17:45434->119.29.29.29:53: i/o timeout"
time="2019-01-09T14:16:31+08:00" level=warning msg="DNSPod Fail: read udp 10.5.10.17:39023->119.29.29.29:53: i/o timeout"
time="2019-01-09T14:16:51+08:00" level=warning msg="DNSPod Fail: read udp 10.5.10.17:53545->119.29.29.29:53: i/o timeout"
time="2019-01-09T14:25:09+08:00" level=warning msg="DNSPod Fail: read udp 10.5.10.17:49066->119.29.29.29:53: i/o timeout"
time="2019-01-09T14:33:49+08:00" level=warning msg="DNSPod Fail: read udp 10.5.10.17:53859->119.29.29.29:53: i/o timeout"
time="2019-01-09T14:48:38+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:39975->202.102.128.68:53: i/o timeout"
time="2019-01-09T15:04:15+08:00" level=warning msg="DNSPod Fail: read udp 10.5.10.17:47704->119.29.29.29:53: i/o timeout"
time="2019-01-09T15:04:15+08:00" level=warning msg="DNSPod Fail: read udp 10.5.10.17:37044->119.29.29.29:53: i/o timeout"
time="2019-01-09T15:10:52+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:36591->202.102.128.68:53: i/o timeout"
time="2019-01-09T15:25:04+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:36067->202.102.128.68:53: i/o timeout"
time="2019-01-09T15:25:04+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:47766->202.102.128.68:53: i/o timeout"
time="2019-01-09T15:26:44+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:37450->202.102.128.68:53: i/o timeout"
time="2019-01-09T15:26:45+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:46488->202.102.128.68:53: i/o timeout"
time="2019-01-09T15:26:45+08:00" level=warning msg="114 Fail: read udp 10.5.10.17:51549->114.114.114.114:53: i/o timeout"
time="2019-01-09T15:26:45+08:00" level=warning msg="114 Fail: read udp 10.5.10.17:35030->114.114.114.114:53: i/o timeout"
time="2019-01-09T15:26:46+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:43379->202.102.128.68:53: i/o timeout"
time="2019-01-09T16:03:24+08:00" level=warning msg="DNSPod Fail: read udp 10.5.10.17:58285->119.29.29.29:53: i/o timeout"
time="2019-01-09T16:28:40+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:52312->202.102.128.68:53: i/o timeout"
time="2019-01-09T16:28:40+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:45044->202.102.128.68:53: i/o timeout"
time="2019-01-09T16:28:40+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:45560->202.102.128.68:53: i/o timeout"
time="2019-01-09T16:50:21+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:47981->202.102.128.68:53: i/o timeout"
time="2019-01-09T17:24:48+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:39914->202.102.128.68:53: i/o timeout"
time="2019-01-09T17:29:58+08:00" level=warning msg="114 Fail: read udp 10.5.10.17:50833->114.114.114.114:53: i/o timeout"
time="2019-01-09T18:28:35+08:00" level=warning msg="CNC Fail: read udp 10.5.10.17:50942->202.102.128.68:53: i/o timeout"

**Comment by Alion548** [comment]
我也遇到类似情况

**Comment by ChanthMiao** [comment]
我也遇到了类似的情况，一堆i/o timout

**Comment by shawn1m** [comment]
可以试下 v1.5-rc7。
