### ISSUE TITLE
gfwlist.txt 现在最新版本还支持吗

### ISSUE THREAD

**Issue by zhaoguomanong** [shawn1m/overture#128]
配置信息如下：

其中gfwlist.txt从如下地址获得

wget -c -N https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt
wget -c -N https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

貌似现在最新的配置里面去除了"DomainBase64Decode": true,

但是gfwlist.txt里面是base64编码的，从overture运行日志看来

time="2019-02-08T11:59:19+08:00" level=info msg="Load domain ./gfwlist.txt successful with 2880 records "

应该是把每行当一个记录，感觉没有进行解码就直接Load进去了，

{
  "BindAddress": "127.8.8.8:53",
  "PrimaryDNS": [
    {
      "Name": "ISPDNS1",
      "Address": "219.239.26.42:53",
      "Protocol": "udp",
      "SOCKS5Address": "",
      "Timeout": 6,
      "EDNSClientSubnet": {
        "Policy": "disable",
        "ExternalIP": ""
      }
    },
    {
      "Name": "ISPDNS2",
      "Address": "124.207.160.106:53",
      "Protocol": "udp",
      "SOCKS5Address": "",
      "Timeout": 6,
      "EDNSClientSubnet": {
        "Policy": "disable",
        "ExternalIP": ""
      }
    },
    {
      "Name": "DNSPod",
      "Address": "119.29.29.29:53",
      "Protocol": "udp",
      "SOCKS5Address": "",
      "Timeout": 6,
      "EDNSClientSubnet": {
        "Policy": "disable",
        "ExternalIP": ""
      }
    },
    {
      "Name": "AliDNS",
      "Address": "223.5.5.5:53",
      "Protocol": "udp",
      "SOCKS5Address": "",
      "Timeout": 6,
      "EDNSClientSubnet": {
        "Policy": "disable",
        "ExternalIP": ""
      }
    }
  ],
  "AlternativeDNS": [
    {
      "Name": "OpenDNS1",
      "Address": "208.67.222.222:443",
      "Protocol": "tcp",
      "SOCKS5Address": "",
      "Timeout": 6,
      "EDNSClientSubnet": {
        "Policy": "disable",
        "ExternalIP": ""
      }
    },
    {
      "Name": "OpenDNS2",
      "Address": "208.67.220.220:443",
      "Protocol": "tcp",
      "SOCKS5Address": "",
      "Timeout": 6,
      "EDNSClientSubnet": {
        "Policy": "disable",
        "ExternalIP": ""
      }
    }
  ],
  "OnlyPrimaryDNS": false,
  "IPv6UseAlternativeDNS": false,
  "IPNetworkFile": {
    "Primary": "./china_ip_list.txt",
    "Alternative": "./ip_network_alternative_sample"
  },
  "DomainFile": {
    "Primary": "./domain_primary_sample",
    "Alternative": "./gfwlist.txt"
  },
  "HostsFile": "./hosts_sample",
  "MinimumTTL": 600,
  "CacheSize" : 65535,
  "RejectQtype": [255]
}

**Comment by zhaoguomanong** [comment]
求大佬支招现在overture使用https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt的正确姿势．

目前overture版本v1.4

感谢!

**Comment by shawn1m** [comment]
不会支持，不过 v1.5-rc4 开始支持正则表达式，可以自行探索。
