### ISSUE TITLE
Client get timeout if the result is in ip_network_primary_sample but domain not in domain_primary_sample 

### ISSUE THREAD

**Issue by Amankwah** [shawn1m/overture#130]
Below is the log when I dig jd.com under CentOS 7 and got timeout.

DEBU[0005] Question from 127.0.0.1: ;jd.com.	IN	 A      
DEBU[0005] Domain primary match fail                    
DEBU[0005] Domain alternative match fail                
DEBU[0005] Answer from 114 DNS: jd.com.	54	IN	A	120.52.148.118 
DEBU[0005] Try to match response ip address with IP network 
DEBU[0005] Matched: IP network primary 120.52.148.118 120.52.0.0/16 
DEBU[0005] Finally use primary DNS                      
DEBU[0005] Answer from PPPoE DNS 1: jd.com.	600	IN	A	120.52.148.118 
DEBU[0005] Answer from PPPoE DNS 2: jd.com.	600	IN	A	120.52.148.118 
DEBU[0011] Question from 127.0.0.1: ;jd.com.	IN	 A      
DEBU[0011] Domain primary match fail                    
DEBU[0011] Domain alternative match fail                
DEBU[0011] Answer from PPPoE DNS 1: jd.com.	600	IN	A	120.52.148.118 
DEBU[0011] Try to match response ip address with IP network 
DEBU[0011] Matched: IP network primary 120.52.148.118 120.52.0.0/16 
DEBU[0011] Finally use primary DNS                      
DEBU[0011] Answer from 114 DNS: jd.com.	48	IN	A	120.52.148.118 
DEBU[0011] Answer from PPPoE DNS 2: jd.com.	600	IN	A	120.52.148.118 
DEBU[0017] Question from 127.0.0.1: ;jd.com.	IN	 A      
DEBU[0017] Domain primary match fail                    
DEBU[0017] Domain alternative match fail                
DEBU[0017] Answer from PPPoE DNS 2: jd.com.	600	IN	A	120.52.148.118 
DEBU[0017] Try to match response ip address with IP network 
DEBU[0017] Matched: IP network primary 120.52.148.118 120.52.0.0/16 
DEBU[0017] Finally use primary DNS                      
DEBU[0017] Answer from PPPoE DNS 1: jd.com.	600	IN	A	120.52.148.118 
DEBU[0017] Answer from 114 DNS: jd.com.	42	IN	A	120.52.148.118

**Comment by bborn2** [comment]
master branch？

master分支的dispathcer.go的exchange方法有bug， 这种case return nil

我理解是作者重构还没有完成

**Comment by Amankwah** [comment]
> master branch？
> 
> master分支的dispathcer.go的exchange方法有bug， 这种case return nil
> 
> 我理解是作者重构还没有完成

这个仓库只有master分支啊。看了一下代码，那个方法最后只处理了current是alternative的情况，然后返回nil，看来应该是没垂柳完成。

**Comment by bborn2** [comment]
用tag v1.5-rc3

**Comment by Amankwah** [comment]
谢谢 @bborn2 。
