### ISSUE TITLE
传入IP为内网IP时，出现i/o timeout

### ISSUE THREAD

**Issue by koalang** [shawn1m/overture#132]
用的腾讯云，内网IP：10.135.61.204
overture(绑定53端口)作为unbound(绑定5353端口)的上游DNS server，查询unbound时发现

> dig @127.0.0.1 -p 53 www.baidu.com
显示正常
当>  dig @127.0.0.1 -p 5353 www.baidu.com
时
显示：
> DNSPod Fail: read udp 10.135.61.204:31163->119.29.29.29:53: i/o timeout
当传入IP是内网IP时，会出现i/o time

翻看issues 不止我一个出现这个问题
https://github.com/shawn1m/overture/issues/107

ExternalIP我设置为本机公网IP，如果留空也会出现i/o timeout

**Comment by shawn1m** [comment]
这个我没法复现，如果是偶尔出现的 timeout 可以接受，udp 本来就不保证可靠性而且还有服务端网络连接各种影响，可以试试 v1.5-rc7。
