### ISSUE TITLE
1.5-rc4 缓存返回结果速度问题 

### ISSUE THREAD

**Issue by rampageX** [shawn1m/overture#133]
rc3 上如果域名被缓存了，查询返回响应速度是几毫秒，到了 rc4 变成几十上百毫秒了：

rc3:

> <13>Mar  4 22:24:58 overture: Starting overture DEBUG mode...
> INFO[0000] Overture v1.5-rc3
> INFO[0000] If you need any help, please visit the project repository: https://github.com/shawn1m/overture
> INFO[0000] Load domain /opt/etc/domain_acclist.txt successful with 6820 records
> INFO[0000] Load domain /opt/etc/domain_gfwlist.txt successful with 5739 records
> INFO[0000] Load /opt/etc/cn.zone successful
> INFO[0000] Load /opt/etc/us.zone successful
> INFO[0000] Minimum TTL is 300
> INFO[0000] CacheSize is 9999
> INFO[0000] Load hosts file successful
> INFO[0000] Start overture on 0.0.0.0:5554
> DEBU[0005] Question from 127.0.0.1: ;sta-op.douyucdn.cn.	IN	 A
> DEBU[0005] Matched: Domain primary sta-op.douyucdn.cn cn
> DEBU[0005] Finally use primary DNS
> DEBU[0005] Answer from Deadwood: sta-op.douyucdn.cn.	492	IN	CNAME	sta-op.douyucdn.cn.m.alikunlun.com.
> DEBU[0005] Answer from Deadwood: sta-op.douyucdn.cn.m.alikunlun.com.	492	IN	A	111.12.88.220
> DEBU[0005] Answer from Deadwood: sta-op.douyucdn.cn.m.alikunlun.com.	492	IN	A	111.12.88.221
> DEBU[0005] Answer from Deadwood: sta-op.douyucdn.cn.m.alikunlun.com.	492	IN	A	111.12.88.236
> DEBU[0005] Answer from Deadwood: sta-op.douyucdn.cn.m.alikunlun.com.	492	IN	A	111.12.88.217
> DEBU[0005] Answer from Deadwood: sta-op.douyucdn.cn.m.alikunlun.com.	492	IN	A	111.12.88.219
> DEBU[0005] Answer from Deadwood: sta-op.douyucdn.cn.m.alikunlun.com.	492	IN	A	111.12.88.218
> DEBU[0005] Answer from Deadwood: sta-op.douyucdn.cn.m.alikunlun.com.	492	IN	A	111.12.88.216
> DEBU[0005] Answer from Deadwood: sta-op.douyucdn.cn.m.alikunlun.com.	492	IN	A	111.12.88.237
> DEBU[0005] Cached: sta-op.douyucdn.cn. 1
> DEBU[0005] Answer from FASTDNS: sta-op.douyucdn.cn.	492	IN	CNAME	sta-op.douyucdn.cn.m.alikunlun.com.
> DEBU[0005] Answer from FASTDNS: sta-op.douyucdn.cn.m.alikunlun.com.	492	IN	A	111.12.88.216
> DEBU[0005] Answer from FASTDNS: sta-op.douyucdn.cn.m.alikunlun.com.	492	IN	A	111.12.88.237
> DEBU[0005] Answer from FASTDNS: sta-op.douyucdn.cn.m.alikunlun.com.	492	IN	A	111.12.88.236
> DEBU[0005] Answer from FASTDNS: sta-op.douyucdn.cn.m.alikunlun.com.	492	IN	A	111.12.88.218
> DEBU[0005] Answer from FASTDNS: sta-op.douyucdn.cn.m.alikunlun.com.	492	IN	A	111.12.88.219
> DEBU[0005] Answer from FASTDNS: sta-op.douyucdn.cn.m.alikunlun.com.	492	IN	A	111.12.88.217
> DEBU[0005] Answer from FASTDNS: sta-op.douyucdn.cn.m.alikunlun.com.	492	IN	A	111.12.88.220
> DEBU[0005] Answer from FASTDNS: sta-op.douyucdn.cn.m.alikunlun.com.	492	IN	A	111.12.88.221
> DEBU[0025] Question from 127.0.0.1: ;sta-op.douyucdn.cn.	IN	 A

rc3 dig:

> ; <<>> DiG 9.13.1 <<>> -p 5554 sta-op.douyucdn.cn
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49203
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 9, AUTHORITY: 0, ADDITIONAL: 0
> 
> ;; QUESTION SECTION:
> ;sta-op.douyucdn.cn.		IN	A
> 
> ;; ANSWER SECTION:
> sta-op.douyucdn.cn.	492	IN	CNAME	sta-op.douyucdn.cn.m.alikunlun.com.
> sta-op.douyucdn.cn.m.alikunlun.com. 492	IN A	111.12.88.220[广西桂林市 移动]
> sta-op.douyucdn.cn.m.alikunlun.com. 492	IN A	111.12.88.221[广西桂林市 移动]
> sta-op.douyucdn.cn.m.alikunlun.com. 492	IN A	111.12.88.236[广西桂林市 移动]
> sta-op.douyucdn.cn.m.alikunlun.com. 492	IN A	111.12.88.217[广西桂林市 移动]
> sta-op.douyucdn.cn.m.alikunlun.com. 492	IN A	111.12.88.219[广西桂林市 移动]
> sta-op.douyucdn.cn.m.alikunlun.com. 492	IN A	111.12.88.218[广西桂林市 移动]
> sta-op.douyucdn.cn.m.alikunlun.com. 492	IN A	111.12.88.216[广西桂林市 移动]
> sta-op.douyucdn.cn.m.alikunlun.com. 492	IN A	111.12.88.237[广西桂林市 移动]
> 
> ;; Query time: 2 msec
> ;; SERVER: 127.0.0.1[本机地址]#5554(127.0.0.1[本机地址])
> ;; WHEN: Mon Mar 04 22:25:23 CST 2019
> ;; MSG SIZE  rcvd: 212

rc4:

> INFO[2019-03-04 14:30:37] Overture v1.5-rc4
> INFO[2019-03-04 14:30:37] If you need any help, please visit the project repository: https://github.com/shawn1m/overture
> INFO[2019-03-04 14:30:37] Load domain /opt/etc/domain_acclist.txt successful with 6820 records
> INFO[2019-03-04 14:30:37] Load domain /opt/etc/domain_gfwlist.txt successful with 5739 records
> INFO[2019-03-04 14:30:37] Load /opt/etc/cn.zone successful
> INFO[2019-03-04 14:30:37] Load /opt/etc/us.zone successful
> INFO[2019-03-04 14:30:37] Minimum TTL is 300
> INFO[2019-03-04 14:30:37] CacheSize is 9999
> INFO[2019-03-04 14:30:37] Load hosts file successful
> INFO[2019-03-04 14:30:37] Start overture on 0.0.0.0:5554
> DEBU[2019-03-04 14:30:41] Question from 127.0.0.1: ;sta-op.douyucdn.cn.	IN	 A
> DEBU[2019-03-04 14:30:41] Matched                                       DNS=Primary domain=cn question=sta-op.douyucdn.cn
> DEBU[2019-03-04 14:30:41] Finally use Primary DNS
> DEBU[2019-03-04 14:30:41] Answer from FASTDNS: sta-op.douyucdn.cn.	155	IN	CNAME	sta-op.douyucdn.cn.m.alikunlun.com.
> DEBU[2019-03-04 14:30:41] Answer from FASTDNS: sta-op.douyucdn.cn.m.alikunlun.com.	155	IN	A	111.12.88.216
> DEBU[2019-03-04 14:30:41] Answer from FASTDNS: sta-op.douyucdn.cn.m.alikunlun.com.	155	IN	A	111.12.88.237
> DEBU[2019-03-04 14:30:41] Answer from FASTDNS: sta-op.douyucdn.cn.m.alikunlun.com.	155	IN	A	111.12.88.236
> DEBU[2019-03-04 14:30:41] Answer from FASTDNS: sta-op.douyucdn.cn.m.alikunlun.com.	155	IN	A	111.12.88.218
> DEBU[2019-03-04 14:30:41] Answer from FASTDNS: sta-op.douyucdn.cn.m.alikunlun.com.	155	IN	A	111.12.88.219
> DEBU[2019-03-04 14:30:41] Answer from FASTDNS: sta-op.douyucdn.cn.m.alikunlun.com.	155	IN	A	111.12.88.217
> DEBU[2019-03-04 14:30:41] Answer from FASTDNS: sta-op.douyucdn.cn.m.alikunlun.com.	155	IN	A	111.12.88.220
> DEBU[2019-03-04 14:30:41] Answer from FASTDNS: sta-op.douyucdn.cn.m.alikunlun.com.	155	IN	A	111.12.88.221
> DEBU[2019-03-04 14:30:41] Cached: sta-op.douyucdn.cn. 1
> DEBU[2019-03-04 14:30:41] Cache Hit: sta-op.douyucdn.cn. 1
> DEBU[2019-03-04 14:30:43] Question from 127.0.0.1: ;sta-op.douyucdn.cn.	IN	 A
> DEBU[2019-03-04 14:30:43] Matched                                       DNS=Primary domain=cn question=sta-op.douyucdn.cn
> DEBU[2019-03-04 14:30:43] Finally use Primary DNS
> DEBU[2019-03-04 14:30:43] Cache Hit: sta-op.douyucdn.cn. 1
> DEBU[2019-03-04 14:30:43] Cached: sta-op.douyucdn.cn. 1
> DEBU[2019-03-04 14:30:43] Cache Hit: sta-op.douyucdn.cn. 1
> DEBU[2019-03-04 14:30:46] Question from 127.0.0.1: ;sta-op.douyucdn.cn.	IN	 A
> DEBU[2019-03-04 14:30:46] Matched                                       DNS=Primary domain=cn question=sta-op.douyucdn.cn
> DEBU[2019-03-04 14:30:46] Finally use Primary DNS
> DEBU[2019-03-04 14:30:46] Cache Hit: sta-op.douyucdn.cn. 1
> DEBU[2019-03-04 14:30:46] Cache Hit: sta-op.douyucdn.cn. 1
> DEBU[2019-03-04 14:30:46] Cached: sta-op.douyucdn.cn. 1

rc4 dig:

> ; <<>> DiG 9.13.1 <<>> -p 5554 sta-op.douyucdn.cn
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33253
> ;; flags: qr ra; QUERY: 1, ANSWER: 9, AUTHORITY: 0, ADDITIONAL: 0
> 
> ;; QUESTION SECTION:
> ;sta-op.douyucdn.cn.		IN	A
> 
> ;; ANSWER SECTION:
> sta-op.douyucdn.cn.	155	IN	CNAME	sta-op.douyucdn.cn.m.alikunlun.com.
> sta-op.douyucdn.cn.m.alikunlun.com. 155	IN A	111.12.88.216[广西桂林市 移动]
> sta-op.douyucdn.cn.m.alikunlun.com. 155	IN A	111.12.88.237[广西桂林市 移动]
> sta-op.douyucdn.cn.m.alikunlun.com. 155	IN A	111.12.88.236[广西桂林市 移动]
> sta-op.douyucdn.cn.m.alikunlun.com. 155	IN A	111.12.88.218[广西桂林市 移动]
> sta-op.douyucdn.cn.m.alikunlun.com. 155	IN A	111.12.88.219[广西桂林市 移动]
> sta-op.douyucdn.cn.m.alikunlun.com. 155	IN A	111.12.88.217[广西桂林市 移动]
> sta-op.douyucdn.cn.m.alikunlun.com. 155	IN A	111.12.88.220[广西桂林市 移动]
> sta-op.douyucdn.cn.m.alikunlun.com. 155	IN A	111.12.88.221[广西桂林市 移动]
> 
> ;; Query time: 136 msec
> ;; SERVER: 127.0.0.1[本机地址]#5554(127.0.0.1[本机地址])
> ;; WHEN: Mon Mar 04 22:30:46 CST 2019
> ;; MSG SIZE  rcvd: 212

2ms vs 136ms ！看起来 rc4 判断缓存命中后，没有直接返回缓存结果，而是又去两个域名列表查询了一下才返回结果？

**Comment by Alion548** [comment]
建议缓存采用懒更新方式：即判断缓存已过期（实际TTL），先返回缓存给DNS客户端，再异步更新缓存结果。

**Comment by rampageX** [comment]
RC5 好了。
