### ISSUE TITLE
AD域成员和IO time out的问题

### ISSUE THREAD

**Issue by dustiarmor** [shawn1m/overture#135]
第一个问题，是AD域中工作站的问题：
我的主机是 ws01.xx.test，在log中生成如下报错：
Question from 10.255.207.48: ;www.baidu.com.xx.test.        IN       A 
DEBU[2019-03-07 10:35:26] Domain Primary match fail                    
DEBU[2019-03-07 10:35:26] Domain Alternative match fail                
DEBU[2019-03-07 10:35:26] Primary DNS answer is empty, finally use alternative DNS 
DEBU[2019-03-07 10:35:28] Question from 10.255.207.48: ;www.baidu.com.xx.test.        IN       AAAA 
DEBU[2019-03-07 10:35:28] Domain Primary match fail                    
DEBU[2019-03-07 10:35:28] Domain Alternative match fail                
DEBU[2019-03-07 10:35:28] Primary DNS answer is empty, finally use alternative DNS 
DEBU[2019-03-07 10:35:30] Question from 10.255.207.48: ;www.baidu.com.  IN       A 
DEBU[2019-03-07 10:35:30] Domain Primary match fail                    
DEBU[2019-03-07 10:35:30] Domain Alternative match fail                
DEBU[2019-03-07 10:35:30] Answer from DNSPod: www.baidu.com.    1032    IN      CNAME   www.a.shifen.com. 
DEBU[2019-03-07 10:35:30] Answer from DNSPod: www.a.shifen.com. 132     IN      A       163.177.151.110 
DEBU[2019-03-07 10:35:30] Answer from DNSPod: www.a.shifen.com. 132     IN      A       163.177.151.109 
DEBU[2019-03-07 10:35:30] Try to match response ip address with IP network 
DEBU[2019-03-07 10:35:30] IP network match failed, finally use alternative DNS 
DEBU[2019-03-07 10:35:30] Try to match response ip address with IP network 
DEBU[2019-03-07 10:35:30] IP network match failed, finally use alternative DNS 
DEBU[2019-03-07 10:35:30] Try to match response ip address with IP network 
DEBU[2019-03-07 10:35:30] IP network match failed, finally use alternative DNS 
DEBU[2019-03-07 10:35:30] Answer from OpenDNS: www.baidu.com.   935     IN      CNAME   www.a.shifen.com. 
DEBU[2019-03-07 10:35:30] Answer from OpenDNS: www.a.shifen.com.        300     IN      A       163.177.151.110 
DEBU[2019-03-07 10:35:30] Answer from OpenDNS: www.a.shifen.com.        300     IN      A       163.177.151.109 
DEBU[2019-03-07 10:35:30] Question from 10.255.207.48: ;www.baidu.com.  IN       AAAA 
DEBU[2019-03-07 10:35:30] Domain Primary match fail                    
DEBU[2019-03-07 10:35:30] Domain Alternative match fail                
DEBU[2019-03-07 10:35:30] Answer from DNSPod: www.baidu.com.    1148    IN      CNAME   www.a.shifen.com. 
DEBU[2019-03-07 10:35:30] Try to match response ip address with IP network 
DEBU[2019-03-07 10:35:30] IP network match failed, finally use alternative DNS 

另外一个报错是：
OpenDNS Fail: read tcp serverIP:47137->208.67.220.220:443: i/o timeout 
config如下：
{
  "BindAddress": ":53",
  "DebugHTTPAddress": "127.0.0.1:5555",
  "PrimaryDNS": [
    {
      "Name": "DNSPod",
      "Address": "119.29.29.29:53",
      "Protocol": "udp",
      "SOCKS5Address": "",
      "Timeout": 6,
      "EDNSClientSubnet": {
        "Policy": "disable",
        "ExternalIP": "",
        "NoCookie": true
      }
    }
  ],
  "AlternativeDNS": [
    {
      "Name": "OpenDNS",
      "Address": "208.67.220.220:443",
      "Protocol": "tcp",
      "SOCKS5Address": "",
      "Timeout": 6,
      "EDNSClientSubnet": {
        "Policy": "disable",
        "ExternalIP": "",
        "NoCookie": true
      }
    }
  ],
  "OnlyPrimaryDNS": false,
  "IPv6UseAlternativeDNS": false,
  "IPNetworkFile": {
    "Primary": "./ip_network_primary_sample",
    "Alternative": "./ip_network_alternative_sample"
  },
  "DomainFile": {
    "Primary": "./domain_primary_sample",
    "Alternative": "./domain_alternative_sample"
  },
  "HostsFile": "./hosts_sample",
  "MinimumTTL": 0,
  "DomainTTLFile" : "./domain_ttl_sample",
  "CacheSize" : 0,
  "RejectQType": [255]
}

这个报错出现在Overture v1.5-rc5，我的服务器是debian 8 ，在Overture 1.3.5.2版本没有出现IO time out的问题。在1.5版本中，有这个报错的时候，可以看到很多TCP链接没有释放
tcp    CLOSING    1      40                10.0.9.109:37832                                          208.67.220.220:https

**Comment by shawn1m** [comment]
AD 域不太了解，从 log 中看是给每个域名加了后缀？
可以试下 rc6，另外 opendns 只是 sample，并不保证可用性，出现 timeout 也很正常。
