### ISSUE TITLE
i/o timeout问题

### ISSUE THREAD

**Issue by itianlang** [shawn1m/overture#137]
`time="2019-03-09 20:19:04" level=warning msg="DNSPod Fail: read udp 172.31.121.103:59997->119.28.28.28:53: i/o timeout"
time="2019-03-09 20:19:09" level=warning msg="DNSPod Fail: read udp 172.31.121.103:52451->119.28.28.28:53: i/o timeout"
time="2019-03-09 20:19:14" level=warning msg="DNSPod Fail: read udp 172.31.121.103:34867->119.28.28.28:53: i/o timeout"
time="2019-03-09 20:19:14" level=warning msg="DNSPod Fail: read udp 172.31.121.103:36902->119.28.28.28:53: i/o timeout"
time="2019-03-09 20:19:14" level=warning msg="DNSPod Fail: read udp 172.31.121.103:56339->119.28.28.28:53: i/o timeout"
time="2019-03-09 20:19:14" level=warning msg="DNSPod Fail: read udp 172.31.121.103:44411->119.28.28.28:53: i/o timeout"
time="2019-03-09 20:19:19" level=warning msg="DNSPod Fail: read udp 172.31.121.103:33119->119.28.28.28:53: i/o timeout"
time="2019-03-09 20:19:19" level=warning msg="DNSPod Fail: read udp 172.31.121.103:44352->119.28.28.28:53: i/o timeout"
time="2019-03-09 20:19:19" level=warning msg="DNSPod Fail: read udp 172.31.121.103:56144->119.28.28.28:53: i/o timeout"
time="2019-03-09 20:20:04" level=warning msg="DNSPod Fail: read udp 172.31.121.103:44163->119.28.28.28:53: i/o timeout"
time="2019-03-09 20:20:09" level=warning msg="DNSPod Fail: read udp 172.31.121.103:43752->119.28.28.28:53: i/o timeout"
time="2019-03-09 20:20:14" level=warning msg="DNSPod Fail: read udp 172.31.121.103:45269->119.28.28.28:53: i/o timeout"
time="2019-03-09 20:20:14" level=warning msg="DNSPod Fail: read udp 172.31.121.103:35957->119.28.28.28:53: i/o timeout"
time="2019-03-09 20:20:14" level=warning msg="DNSPod Fail: read udp 172.31.121.103:36454->119.28.28.28:53: i/o timeout"
time="2019-03-09 20:20:14" level=warning msg="DNSPod Fail: read udp 172.31.121.103:50577->119.28.28.28:53: i/o timeout"
time="2019-03-09 20:20:19" level=warning msg="DNSPod Fail: read udp 172.31.121.103:52500->119.28.28.28:53: i/o timeout"
time="2019-03-09 20:20:19" level=warning msg="DNSPod Fail: read udp 172.31.121.103:58671->119.28.28.28:53: i/o timeout"
time="2019-03-09 20:21:04" level=warning msg="DNSPod Fail: read udp 172.31.121.103:49095->119.28.28.28:53: i/o timeout"`

**频繁出现以上问题，请问是什么情况**

**Comment by shawn1m** [comment]
如果不影响使用这很正常，udp 本来就不保证可靠性
