### ISSUE TITLE
"overture -V"返回版本号有问题

### ISSUE THREAD

**Issue by JACK-THINK** [shawn1m/overture#144]
代码位置https://github.com/shawn1m/overture/blob/88a42ec9862b3043fbc0dadac16ee965e6f96c40/main/main.go#L40

此处您使用了`println`函数，使得输出结果自带换行符，相当于输出"v1.5\n"。请更换输出函数以去除末尾的换行符，谢谢。

**Comment by JACK-THINK** [comment]
'overture -V'的输出好像不能用于管道？这是为什么呢？
![Snipaste_2019-03-24_19-16-54](https://user-images.githubusercontent.com/21015855/54878549-6ab09200-4e69-11e9-8a37-f5a7983c2a9c.png)

**Comment by lybtongji** [comment]
将 stderr 重定向到 stdout 即可
![](https://i.loli.net/2019/03/27/5c9b2511f1db2.png)

**Comment by JACK-THINK** [comment]
> 将 stderr 重定向到 stdout 即可
> ![](https://camo.githubusercontent.com/177332a8f563dea4c14c2088bba84f6942d15e9e/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30332f32372f356339623235313166316462322e706e67)

确实可以解决问题。不过这不太符合Linux标准，不知作者是否计划更正。
