### ISSUE TITLE
domain匹配问题

### ISSUE THREAD

**Issue by lix5027** [shawn1m/overture#149]
发现一个问题,
primary表里面如果有le.com
alternative表里有google.com

那么我查询google.com的时候,会被le.com匹配,从而使用primay dns

**Comment by shawn1m** [comment]
目前是全正则匹配，如果需要完全匹配可以自行搜索姿势，后面有时间会做成自选匹配策略。

**Comment by shawn1m** [comment]
This problem would be solved by the newest version and an appropriate matcher.
