### ISSUE TITLE
Overture 1.5 returns SERVFAIL

### ISSUE THREAD

**Issue by isjerryxiao** [shawn1m/overture#151]
1.4 is fine, without any problem, 1.5 always gives me a SERVFAIL somehow  
![image](https://user-images.githubusercontent.com/14978021/56132907-cfb95c80-5fbd-11e9-9ed7-be6751ca3e9b.png)

![image](https://user-images.githubusercontent.com/14978021/56132856-a4367200-5fbd-11e9-9410-a5eeb0a9555d.png)

Other domains can be correctly resolved. Tried google and baidu.com.

**Comment by shawn1m** [comment]
Try to check the config file changes and show the full log?

**Comment by isjerryxiao** [comment]
[This](https://aur.archlinux.org/cgit/aur.git/tree/config.json?h=overture) is my config  
And I've enabled verbose mode in the screenshots above, I don't quite understand what do you mean by 

> show the full log.

**Comment by isjerryxiao** [comment]
It's weird, I can't reproduce the same error now, maybe it's some sort of network issue.

**Comment by shawn1m** [comment]
> [This](https://aur.archlinux.org/cgit/aur.git/tree/config.json?h=overture&id=3a19026dd6789c949bc7de4a7f8c1e4c022c2081) is my config
> And I've enabled verbose mode in the screenshots above, I don't quite understand what do you mean by
> 
> > show the full log.

my mistake, just ignore it
