### ISSUE TITLE
toggle option to turn off 'Custom IP network Dispatcher'

### ISSUE THREAD

**Issue by april4** [shawn1m/overture#152]
provide option to turn off 'Custom IP network Dispatcher', or auto turn off(i.e. Like 'WhenPrimaryDNSAnswerNoneUse', only use alternative DNS when response of PrimaryDNS exists and there is no ANSWER SECTION in it.) this when:  
```
  "IPNetworkFile": {
    "Primary": "",
    "Alternative": ""
  },
```
'IPNetworkFile' path is empty.  
Otherwise it will always use alternative DNS, when 'IPNetworkFile' path is empty, twice time then only use primary DNS.  
If i fill 'ip_network_primary_sample' with all North America network CIDR(estimate 75k line), this will cause the query time more slower(7~15s).

**Comment by shawn1m** [comment]
Try 0.0.0.0/0 ?

**Comment by april4** [comment]
> Try 0.0.0.0/0 ?

Current workaround is add those:  
```
0.0.0.0/1  
255.255.255.255/1
```
to 'ip_network_primary_sample'
