### ISSUE TITLE
上游DNS配置 Google DNS over TLS 问题

### ISSUE THREAD

**Issue by kiolygenius** [shawn1m/overture#154]
上游配置 dns 协议 tcp-tls, 地址 dns.google:853@8.8.8.8, 日志输出以下错误

Dial DNS-over-TLS upstream failed: x509: cannot validate certificate for 8.8.8.8 because it doesn't contain any IP SANs

[Version 1.5 final]

**Comment by shawn1m** [comment]
https://developers.google.com/speed/public-dns/docs/dns-over-tls

**Comment by shawn1m** [comment]
Maybe dns.google?

This section gives an overview of DNS-over-TLS operation when talking to the Google Public DNS resolver (with the name dns.google).

**Comment by shawn1m** [comment]
```json
{    
      "Address": "dns.google:853@8.8.8.8",
      "Protocol": "tcp-tls"
}
```

I use this config and it works, maybe there are some network environment problems you must solve first.
