### ISSUE TITLE
通过执行NSLOOKUP , 出现**(root)  ??? unknown type 41 ???**或着DNS request timed out.请问大神，这种情况是什么原因导致？

### ISSUE THREAD

**Issue by 18600686177** [shawn1m/overture#155]
通过执行NSLOOKUP , 出现**(root)  ??? unknown type 41 ???**或着DNS request timed out.请问大神，这种情况是什么原因导致？
![image](https://user-images.githubusercontent.com/30793175/57509392-b8f4f400-7336-11e9-8807-39a42cc3c318.png)

**Comment by shawn1m** [comment]
https://github.com/chengr28/Pcap_DNSProxy/issues/15

**Comment by rampageX** [comment]
![2019-11-06_001832](https://user-images.githubusercontent.com/994081/68225349-3fab3500-002b-11ea-8cdc-a32278ce377a.jpg)
