### ISSUE TITLE
hostfile seems not work

### ISSUE THREAD

**Issue by banditsmile** [shawn1m/overture#16]
hostfile config
```
127.0.0.1 localhost
192.168.31.182	xunlei_com
```

overture in debug mode
```
DEBU[0149] Question: ;xunlei_com.	IN	 NS                
DEBU[0149] Domain match fail, try to use primary DNS    
DEBU[0149] Primary DNS answer is empty, finally use alternative DNS
```

nslook up result
```
nslookup -q=ns xunlei_com
Server:192.168.31.182
Address:192.168.31.182#53
** server can`t find xunlei_com:NXDOMAIN
```

i used this version
https://github.com/shawn1m/overture/releases/download/1.3.1/overture-linux-amd64.zip

**Comment by shawn1m** [comment]
是只有查询 NS 记录时才出现的吧。我在写 Hosts 逻辑的时候只把一般情况下的 A 记录和 AAAA 记录允许使用 Hosts，NS 这种记录不太适合自定义，所以没有放进来。

**Comment by rosynirvana** [comment]
呃，这是哪个nslookup的实现呐，hosts按linux或windows的文档的解释，都是不该含NS record的吧？

**Comment by shawn1m** [comment]
@rosynirvana 他加了一个  -q=ns 的参数，所以 nslookup 就去请求 NS 记录了，NS 这种记录还是不要能自定义的为好。
