### ISSUE TITLE
请教一个问题，我在服务器上搭建完成后，只让内网设备使用，不想公开在公网上

### ISSUE THREAD

**Issue by tudi1909** [shawn1m/overture#160]
不知道这样功能可否实现？
感谢！

**Comment by ysc3839** [comment]
如果内网的外网是两个不同的网卡的话，设置绑定地址即可。
https://github.com/shawn1m/overture/blob/089a14d8b0804be61d9cad0755d2d30c40a1a85a/config.sample.json#L2
否则的话应该只能使用操作系统的防火墙来实现。

**Comment by shawn1m** [comment]
> 如果内网的外网是两个不同的网卡的话，设置绑定地址即可。
> 
> https://github.com/shawn1m/overture/blob/089a14d8b0804be61d9cad0755d2d30c40a1a85a/config.sample.json#L2
> 
> 
> 否则的话应该只能使用操作系统的防火墙来实现。

正解，不对网段公开（扫描都扫不到）最好还是用操作系统的防火墙实现。
