### ISSUE TITLE
Overture独立使用

### ISSUE THREAD

**Issue by wenmangbo** [shawn1m/overture#163]
感觉overture 可以独立使用。但是很多人要配合 dnsmasq使用。
这两种有什么优缺点

**Comment by ffftwo** [comment]
> 感觉overture 可以独立使用。但是很多人要配合 dnsmasq使用。
> 这两种有什么优缺点

跟使用场景有关吧, 比如我是在openwrt路由器上把overture当dnsmasq的上游来用, 需要用到dnsmasq的ipset功能, dnsmasq同时也是dhcp服务器, 能够维护本地主机名的动态解析, 另外dnsmasq做为dns缓存服务器也有相对丰富的选项可以调整.

**Comment by wenmangbo** [comment]
谢谢，今天使用的时候发现一个问题。双wan口。其中一条wan失效的时候。overture会导致cpu占用过高。


ime="2019-07-19 12:06:19" level=warning msg="Google Fail: Send question message failed"
time="2019-07-19 12:06:19" level=warning msg="Google Fail: Send question message failed"
time="2019-07-19 12:06:19" level=warning msg="DNSPod Fail: Send question message failed"
time="2019-07-19 12:06:19" level=warning msg="Google Fail: Send question message failed"
time="2019-07-19 12:06:20" level=warning msg="Google Fail: Send question message failed"
time="2019-07-19 12:06:20" level=warning msg="DNSPod Fail: Send question message failed"
time="2019-07-19 12:06:20" level=warning msg="Google Fail: Send question message failed"
time="2019-07-19 12:06:20" level=warning msg="DNSPod Fail: Send question message failed"
time="2019-07-19 12:06:20" level=warning msg="Google Fail: Send question message failed"
time="2019-07-19 12:06:20" level=warning msg="Google Fail: Send question message failed"
time="2019-07-19 12:06:20" level=warning msg="DNSPod Fail: Send question message failed"
time="2019-07-19 12:06:20" level=warning msg="Google Fail: Send question message failed"
time="2019-07-19 12:06:21" level=warning msg="Google Fail: Send question message failed"
time="2019-07-19 12:06:21" level=warning msg="DNSPod Fail: Send question message failed"
time="2019-07-19 12:06:21" level=warning msg="Google Fail: Send question message failed"
time="2019-07-19 12:06:21" level=warning msg="Google Fail: Send question message failed"
time="2019-07-19 12:06:21" level=warning msg="Google Fail: Send question message failed"
time="2019-07-19 12:06:21" level=warning msg="Google Fail: Send question message failed"
time="2019-07-19 12:06:21" level=warning msg="Google Fail: Send question message failed"
time="2019-07-19 12:06:21" level=warning msg="DNSPod Fail: Send question message failed"
time="2019-07-19 12:06:21" level=warning msg="Google Fail: Send question message failed"
time="2019-07-19 12:06:21" level=warning msg="Google Fail: Send question message failed"
time="2019-07-19 12:06:21" level=warning msg="Google Fail: Send question message failed"
time="2019-07-19 12:06:22" level=warning msg="DNSPod Fail: Send question message failed"

**Comment by shawn1m** [comment]
目前还没有熔断机制，或许未来会有。

**Comment by wenmangbo** [comment]
非常好用的一个软件。很简单，我这种小白都可以用的比较好的。
