### ISSUE TITLE
v1.6-rc4 自定义 hosts 文件解析出错！

### ISSUE THREAD

**Issue by wang20150419** [shawn1m/overture#173]
host file:

2404:6800:4008:c06::71 www.abc.com
111.111.111.111 *.abc.com

v1.4 解析结果：
    dig www.abc.com AAAA --> 返回 2404:6800:4008:c06::71
    dig www.abc.com --> 返回 111.111.111.111
这个结果是我期望的，完全按自定义的 hosts 文件解析。

但是，同样的配置文件，
v1.6-rc4 解析结果：
     dig www.abc.com AAAA --> 返回 2404:6800:4008:c06::71  （正确！）
     dig www.abc.com --> 返回 23.23.23.23  （这个结果是 www.abc.com 对应的真实IP地址，
                            而不是我在 hosts 文件里配置的 111.111.111.111，解析错误！）

希望能恢复到 v1.4的解析结果。

**Comment by shawn1m** [comment]
Regular expression is the matcher by default, you may try "suffix-tree" matcher which will match by the suffix.
