### ISSUE TITLE
使用特定上级 dns 时解析包错误，返回服务器错误且 answer 为空[附抓包]

### ISSUE THREAD

**Issue by wen-long** [shawn1m/overture#174]
如何复现：

使用 https://github.com/AdguardTeam/dnsproxy 作为 overture 上级
```
dnsproxy -z -v -p 5454 -b 114.114.114.114:53 -u https://dns.google/dns-query
```

dig cdn.segmentfault.com 向 overture 请求

overture 返回空记录，但 wireshark 抓包可见 dnsproxy 返回的是正确的数据，同时 overture 返回包包含错误 Reply code: Server failure (2)

值得注意的是 cdn.segmentfault.com 没有 a 记录，而是通过若干 cname 最终解析到 ip，一般的 dns 服务器都会进行合并

抓包如下
[302.pcap.zip](https://github.com/shawn1m/overture/files/3585421/302.pcap.zip)

**Comment by shawn1m** [comment]
Thanks for the PR!
