### ISSUE TITLE
What's the meaning of PU?

### ISSUE THREAD

**Issue by xtian0313** [shawn1m/overture#178]
I run this program in phicom k3,which  is BCM5301X.
And I download the overture-linux-arm.zip(v1.6-rc4).
What's wrong with my router?
root@Baby:/etc/overture# ./overture-linux-arm -c
PU has no floating point hardware, so it cannot run
269599466671506 GOARM=time182compile using GOARM=5.

**Comment by shawn1m** [comment]
There is no pre-test or guarantee for arm or mips cpu.
