### ISSUE TITLE
建议增加prefetch和上游DNS并发查询功能

### ISSUE THREAD

**Issue by PHCSJC** [shawn1m/overture#179]
prefetch是指，在缓存的域名即将过期时，自动的去查询一次域名（unbound有这个功能），这样的好处是：比如我的浏览器闲置时间较长，DNS里的缓存过期了，此时我再打开google，会明显感觉到有一个域名解析的过程，但如果有prefetch，无论浏览器闲置多久，我再次打开google都很快。

并发查询是指，设置多个上游的TCP DNS，比如同时设置8.8.8.8和1.1.1.1，当有解析时，同时去这2个DNS解析，以最快获得的为准，这样也可以尽量减少DNS查询有时缓慢的问题。

最后感谢大佬的付出。

**Comment by PHCSJC** [comment]
再请问下CacheSize的单位是KB吗？

**Comment by import-yuefeng** [comment]
1. [smartDNS](https://github.com/import-yuefeng/smartDNS) 有在尝试支持这几个， 可以看看呢~

2. 单位是domain数量

**Comment by NyaMisty** [comment]
CacheSize是Cache数组的长度，并不是KB
prefetch我觉得并没有太大用，毕竟TTL最少也会在五分钟以上，正常的域名则会更高，每次第一次解析域名之后就会被重新cache，没有必要搞这么复杂
