### ISSUE TITLE
Q: DomainFile.Matcher的含义

### ISSUE THREAD

**Issue by time-river** [shawn1m/overture#180]
文档中提到：
> DomainFile.Matcher: Matching policy and implementation, including "full-list", "full-map", "regex-list" and "suffix-tree"

能否分别为`full-list / full-map / regex-list / suffix-tree / mix-list`举个例子呢？

**Comment by SharerMax** [comment]
full-list / full-map 为全匹配，一种是list结构，一种是map结构
regex-list 按正则表达式匹配
suffix-tree 按域名后缀匹配
mix-list 是按你指定的方式匹配，格式为[domain|regex|keyword|full]:域名

**Comment by goodffd** [comment]
> 

full-map和suffix-tree的区别能举例一下么
