### ISSUE TITLE
更新后用老版本的ip_network_primary_sample报错

### ISSUE THREAD

**Issue by samondlee** [shawn1m/overture#185]
Nov 02 21:12:31 aml overture[3550]: time="2019-11-02 21:12:30" level=error msg="Error parsing IP network CIDR 101.126.0.0/16\r\n: invalid CIDR address: 101.126.0.0/16\r"
Nov 02 21:12:31 aml overture[3550]: time="2019-11-02 21:12:30" level=error msg="Error parsing IP network CIDR 101.128.0.0/22\r\n: invalid CIDR address: 101.128.0.0/22\r"
Nov 02 21:12:31 aml overture[3550]: time="2019-11-02 21:12:30" level=error msg="Error parsing IP network CIDR 101.128.8.0/21\r\n: invalid CIDR address: 101.128.8.0/21\r"
Nov 02 21:12:31 aml overture[3550]: time="2019-11-02 21:12:30" level=error msg="Error parsing IP network CIDR 101.128.16.0/20\r\n: invalid CIDR address: 101.128.16.0/20\r
Nov 02 21:12:31 aml overture[3550]: time="2019-11-02 21:12:30" level=error msg="Error parsing IP network CIDR 101.128.32.0/19\r\n: invalid CIDR address: 101.128.32.0/19\r
Nov 02 21:12:31 aml overture[3550]: time="2019-11-02 21:12:30" level=error msg="Error parsing IP network CIDR 101.129.0.0/16\r\n: invalid CIDR address: 101.129.0.0/16\r"
Nov 02 21:12:31 aml overture[3550]: time="2019-11-02 21:12:30" level=error msg="Error parsing IP network CIDR 101.130.0.0/15\r\n: invalid CIDR address: 101.130.0.0/15\r"
Nov 02 21:12:31 aml overture[3550]: time="2019-11-02 21:12:30" level=error msg="Error parsing IP network CIDR 101.132.0.0/15\r\n: invalid CIDR address: 101.132.0.0/15\r"
Nov 02 21:12:31 aml overture[3550]: time="2019-11-02 21:12:30" level=error msg="Error parsing IP network CIDR 101.134.0.0/17\r\n: invalid CIDR address: 101.134.0.0/17\r"
Nov 02 21:12:31 aml overture[3550]: time="2019-11-02 21:12:30" level=error msg="Error parsing IP network CIDR 101.134.128.0/19\r\n: invalid CIDR address: 101.134.128.0/19

ip_network_primary_sample内容中的一部分,不如该如何修改。。。
改回老版本又没有问题

101.0.0.0/22
101.1.0.0/22
101.2.172.0/22
101.4.0.0/14
101.16.0.0/12
101.32.0.0/14
101.36.0.0/18
101.36.64.0/20
101.36.88.0/21
101.36.96.0/19
101.36.128.0/17
101.37.0.0/16
101.38.0.0/15
101.40.0.0/13
101.48.0.0/15
101.50.8.0/21
101.50.56.0/22
101.52.0.0/16
101.53.100.0/22
101.54.0.0/16
101.55.224.0/21
101.64.0.0/13
101.72.0.0/14
101.76.0.0/15
101.78.0.0/22
101.78.32.0/19
101.80.0.0/12
101.96.0.0/21
101.96.8.0/22
101.96.16.0/20
101.96.128.0/17
101.99.96.0/19
101.101.64.0/19
101.101.100.0/24
101.101.102.0/23
101.101.104.0/21
101.101.112.0/20
101.102.64.0/19
101.102.100.0/23
101.102.102.0/24
101.102.104.0/21
101.102.112.0/20
101.104.0.0/14
101.110.64.0/19
101.110.96.0/20
101.110.116.0/22
101.110.120.0/21
101.120.0.0/14
101.124.0.0/15
101.126.0.0/16
101.128.0.0/22
101.128.8.0/21
101.128.16.0/20
101.128.32.0/19
101.129.0.0/16
101.130.0.0/15
101.132.0.0/15
101.134.0.0/17
101.134.128.0/19
101.134.160.0/20

**Comment by SharerMax** [comment]
Please use `LF` to  replace `CRLF`

**Comment by samondlee** [comment]
> Please use `LF` to replace `CRLF`

wow thanks，and how to configure  ipv4 ipv6 address at same time for one domain in host_sample?

such as

104.25.26.31 u2.dmhy.org
104.25.26.31 tracker.dmhy.org
2606:4700:20::6819:1b1f u2.dmhy.org
2606:4700:20::6819:1b1f tracker.dmhy.org

it says

warning msg="Duplicate entry for host u2.dmhy.org in hosts file, ignored value: 2606:4700:20::6819:1b1f"
Nov 28 10:25:07 aml overture[4320]: time="2019-11-28 10:25:07" level=warning msg="Duplicate entry for host tracker.dmhy.org in hosts file, ignored value: 2606:4700:20

**Comment by SharerMax** [comment]
> > Please use `LF` to replace `CRLF`
> 
> wow thanks，and how to configure ipv4 ipv6 address at same time for one domain in host_sample?
> 
> such as
> 
> 104.25.26.31 u2.dmhy.org
> 104.25.26.31 tracker.dmhy.org
> 2606:4700:20::6819:1b1f u2.dmhy.org
> 2606:4700:20::6819:1b1f tracker.dmhy.org
> 
> it says
> 
> warning msg="Duplicate entry for host u2.dmhy.org in hosts file, ignored value: 2606:4700:20::6819:1b1f"
> Nov 28 10:25:07 aml overture[4320]: time="2019-11-28 10:25:07" level=warning msg="Duplicate entry for host tracker.dmhy.org in hosts file, ignored value: 2606:4700:20

ok, i find and  will try to resolve it
