### ISSUE TITLE
nslookup查询时出现“DNS request timed out.     timeout was 2 seconds.”和“(root)  ??? unknown type 41 ???”提示

### ISSUE THREAD

**Issue by liuxb** [shawn1m/overture#186]
![Untitled](https://user-images.githubusercontent.com/936007/68210063-b20e1c00-000f-11ea-99ed-0e20a14a70e9.png)

搜到了这个 #155 ，但是Pcap_DNSProxy这个项目已经没有了，看不到。
请问这个问题能解决吗，谢谢。

**Comment by rampageX** [comment]
> 那是因为 nslookup 不支持 EDNS0 造成的……提供的 Config.ini 看到 EDNS0 Label 是开启状态，EDNS0 会在每个请求后添加 EDNS0 标签以实现功能，使用的是 OPT 记录，OPT 记录的 ID 是 41，而 nslookup 程序不支持 OPT 记录，所以报告『unknown type 41』了……
> 因为 DNSCurve/DNSCrypt 的实现是必须启用 EDNS0 标签的，而系统本身的解析也会自动忽略这部分的附加记录不会影响解析结果，所以除了在 nslookup 的时候看到有困惑，实际是没有任何影响的ww

From: @chengr28
