### ISSUE TITLE
怎么配置多个上游服务器？

### ISSUE THREAD

**Issue by hleungg** [shawn1m/overture#187]
例如把国内BAT的公共DNS都用上，防止只用一个的时候出现不稳定

**Comment by fems** [comment]
Sample：

 "PrimaryDNS": [
    {
      "Name": "dns1",
      "Address": "1.1.1.1:53",
      "Protocol": "udp",
      "SOCKS5Address": "",
      "Timeout": 6,
      "EDNSClientSubnet": {
        "Policy": "disable",
        "ExternalIP": "",
		"NoCookie": true
      }
    },
    {
      "Name": "dns2",
      "Address": "2.2.2.2:53",
      "Protocol": "udp",
      "SOCKS5Address": "",
      "Timeout": 6,
      "EDNSClientSubnet": {
        "Policy": "disable",
        "ExternalIP": "",
		"NoCookie": true
      }
    },
    {
      "Name": "dns3",
      "Address": "3.3.3.3:53",
      "Protocol": "udp",
      "SOCKS5Address": "",
      "Timeout": 6,
      "EDNSClientSubnet": {
        "Policy": "disable",
        "ExternalIP": "",
		"NoCookie": true
      }
    },
    {
      "Name": "dns4",
      "Address": "4.4.4.4:53",
      "Protocol": "udp",
      "SOCKS5Address": "",
      "Timeout": 6,
      "EDNSClientSubnet": {
        "Policy": "disable",
        "ExternalIP": "",
		"NoCookie": true
      }
    }
  ],

**Comment by xcjiang** [comment]
有多个上游服务器时，是随机选一个用吗？
