### ISSUE TITLE
DebugHTTPAddress port 5555 conflict with android wifi adb

### ISSUE THREAD

**Issue by funnypc** [shawn1m/overture#188]
Just a kindly reminder

due to the default port 5555 of DebugHTTPAddress be same as android wifi adb listener

adb connection will always return 'unauthorised' without fingerprint popup confimation if you got overture running on your android device

have changed it to 5556 in my config.json to solve this successfully

**Comment by shawn1m** [comment]
Thank you very much! I will add it to the README.
