### ISSUE TITLE
hosts file match bug

### ISSUE THREAD

**Issue by yeughe** [shawn1m/overture#190]
hello, when i use overture v1.6cr5，encountered a serious problem that caused the production database to be deleted by mistake. Can you help me fix it ? thanks very much!

Issues:
The hosts_sample is matched by fuzzy keywords by default. My test library is test.xx.com and the production library is xx.com. The analysis of the production library is normal. When the test library is parsed, both the test library ip and the production library ip are returned randomly, resulting in production. The database was deleted by mistake.

solution：
hosts_sample only supports one-to-one resolution

**Comment by SharerMax** [comment]
hosts rule by regex to match, you can try this
`^text.xx.com 1.1.1.1`
`^xx.com 2.2.2.2`

**Comment by shawn1m** [comment]
Please read README before using overture if not just for fun.
Try version v1.6 with "full match" hosts by default
