### ISSUE TITLE
Windows版加载"IPNetworkFile"报错

### ISSUE THREAD

**Issue by linusdrop** [shawn1m/overture#193]
加载"DomainFile" "HostsFile" 无问题，就是"IPNetworkFile"会报错提示：Open IP network file failed: open: the system cannot find the file specifued. x86和amd64版本，win7、win8.1问题都一样。

文件用的是https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt，实际运行结果也是没有走这个表，感觉可能是bug，或是机器运行环境少了什么东西……如能解决非常感谢！

https://i.loli.net/2019/12/18/mrSl9nO4PRLwF28.jpg

**Comment by rampageX** [comment]
没啥问题啊，默认配置下，1.6-rc6。看你截图是 1.5-rc5，用最新版试试。

![2019-12-18_171828](https://user-images.githubusercontent.com/994081/71073056-9ecba000-21ba-11ea-9a32-a0e037f272c6.jpg)

**Comment by linusdrop** [comment]
> 没啥问题啊，默认配置下，1.6-rc6。看你截图是 1.5-rc5，用最新版试试。
> 
> ![2019-12-18_171828](https://user-images.githubusercontent.com/994081/71073056-9ecba000-21ba-11ea-9a32-a0e037f272c6.jpg)

感谢测试，问题是"IPNetworkFile"中的"Alternative"留空就会报错。而分流问题似乎是那份ip表并不完美，看来还要继续鼓捣（虽然不分速度也还行）……

overture和AdGuard、pihole配合使用很不错，在此感谢开发者。
