### ISSUE TITLE
建议ip的匹配使用二叉树搜索或者索引实现

### ISSUE THREAD

**Issue by iikira** [shawn1m/overture#195]
看了一下代码，发现IP的数据结构为数组
```
IPNetworkPrimaryList        []*net.IPNet
IPNetworkAlternativeList    []*net.IPNet
```

这样搜索的性能较低，建议使用二叉搜索树等数据结构，提高搜索性能
参考: https://github.com/emirpasic/gods

**Comment by SharerMax** [comment]
感觉查找的量级并没有达到靠其它算法来提升

**Comment by NyaMisty** [comment]
这不是baidupcs-go的巨佬吗

**Comment by shawn1m** [comment]
Implemented since version v1.7-rc1
