### ISSUE TITLE
EvictRandom

### ISSUE THREAD

**Issue by rosynirvana** [shawn1m/overture#20]
EvictRandom这个实现是不是目前没必要
应该只有InsertMessage可以写Cache entry，一次只能增加一条
然后call EvictRandom
```go
clen := len(c.table)
	if clen < c.capacity {
		return
	}
	i := c.capacity - clen
	for k := range c.table {
		delete(c.table, k)
		i--
		if i == 0 {
			break
		}
	}
```
这个语义应该是把超出capacity的部分删掉，但上下文有读写锁，所以只能是没超或者超了一条

**Comment by shawn1m** [comment]
这算是一种通用性的解决方式，方便其他功能的添加。这段代码来自于https://github.com/skynetservices/skydns/blob/master/cache/cache.go
我在他的基础上做了删减，去掉了目前用不到的 InsertSignature 函数，我考虑为了未来添加多种 Insert 函数应该保留这个通用实现。
