### ISSUE TITLE
建议 hosts 文件 支持  ipv4 和 ipv6 的同时解析（ v1.4 支持）

### ISSUE THREAD

**Issue by wang20150419** [shawn1m/overture#200]
版本 v1.6-rc6

假定有 hosts 文件：
      10.10.10.1  www.123.com
      2001:19f0:ac01::12bf www.123.com

最新版本会忽略 10.10.10.1，提示：
Duplicate entry for host www.123.com in hosts file, ignored value: 10.10.10.1

在 v1.4 版本里，同一域名对应的 ipv4 和  ipv6  地址是可以共存的。解析也正常。
如：
     dig www.123.com AAAA  应答：2001:19f0:ac01::12bf
     dig www.123.com A         应答： 10.10.10.1

 这个特性才是正确的，也是需要的。不知道为啥 v1.6-rc6  反而不支持了。

**Comment by shawn1m** [comment]
Try version v1.6.
