### ISSUE TITLE
windows 7 tls证书问题？

### ISSUE THREAD

**Issue by amtbnagios** [shawn1m/overture#201]
版本
Overture v1.6-rc6（overture-windows-amd64.zip）
Windows 7 Pro 64位 (有windows update补丁到2020-01-15）

配置: 
  "AlternativeDNS": [
      {
        "Name": "dns.google",
        "Address": "dns.google:853@8.8.4.4",
        "Protocol": "tcp-tls",
        "SOCKS5Address": "",
        "Timeout": 6,
        "EDNSClientSubnet": {
          "Policy": "auto",
          "ExternalIP": "61.139.2.6",
          "NoCookie": true
        }
      },
      {
        "Name": "cloudflared",
        "Address": "one.one.one.one:853@1.0.0.1",
        "Protocol": "tcp-tls",
        "SOCKS5Address": "",
        "Timeout": 6,
        "EDNSClientSubnet": {
          "Policy": "disable",
          "ExternalIP": "",
          "NoCookie": true
        }
      }
   ],

日志：
time="2020-01-16 13:33:12" level=debug msg="Finally use Alternative DNS"
time="2020-01-16 13:33:12" level=warning msg="Failed to connect to DNS-over-TLS upstream: x509: certificate is valid for 2001:4860:4860::64, 2001:4860:4860::6464, 2001:4860:4860::8844, 2001:4860:4860::8888, 8.8.4.4, 8.8.8.8, not 8.8.4.4"

time="2020-01-16 13:33:13" level=debug msg="Finally use Alternative DNS"
time="2020-01-16 13:33:13" level=warning msg="Failed to connect to DNS-over-TLS upstream: x509: certificate is valid for 1.1.1.1, 1.0.0.1, 162.159.132.53, 2606:4700:4700::1111, 2606:4700:4700::1001, 2606:4700:4700::64, 2606:4700:4700::6400, 162.159.36.1, 162.159.46.1, not 1.0.0.1"

另外，同一个wifi下,Windows 10又正常的

**Comment by shawn1m** [comment]
It seems that this problem is not caused by overture.
