### ISSUE TITLE
对PrimaryDNS和AlternativeDNS结果取舍的建议

### ISSUE THREAD

**Issue by mewsf** [shawn1m/overture#213]
有些CDN同时部署了国内和国外节点, 而国内节点仅有IPv4, 国外节点是IPv4+IPv6双栈. 这样有的域名通过overture查询结果就是A记录为国内 AAAA记录为国外, 但是系统一般优先走IPv6.
所以建议能支持 如果PrimaryDNS返回了符合IPNetworkFile的结果的话, 完全忽略AlternativeDNS的结果
这样的功能.

**Comment by shawn1m** [comment]
If there are both A and AAAA records received by the system, there must be two requests sent to overture and overture can do something about it only if these AAAA records are blocked entirely in some ways.

**Comment by newcoderlife** [comment]
这个问题有一个类似的例子：netflix。
它有A和AAAA两种解析，netflix会优先使用IPv6网络。在这种情况下无法通过透明代理来解锁netflix。（我尝试了IPv6的tproxy，它会暴露原始地址）。
我们是否可以设置某些域名只返回A记录？比如像[这样](https://mengql12.wordpress.com/2019/03/05/openwrt%e7%94%a8shadowsocks%e8%bf%9e%e6%8e%a5%e6%97%b6%e7%bb%88%e7%ab%af%e8%ae%be%e5%a4%87%e6%97%a0%e6%b3%95%e8%a7%82%e7%9c%8bnetflix%e9%97%ae%e9%a2%98/)。
谢谢！

**Comment by shawn1m** [comment]
> 这个问题有一个类似的例子：netflix。
> 它有A和AAAA两种解析，netflix会优先使用IPv6网络。在这种情况下无法通过透明代理来解锁netflix。（我尝试了IPv6的tproxy，它会暴露原始地址）。
> 我们是否可以设置某些域名只返回A记录？比如像[这样](https://mengql12.wordpress.com/2019/03/05/openwrt%e7%94%a8shadowsocks%e8%bf%9e%e6%8e%a5%e6%97%b6%e7%bb%88%e7%ab%af%e8%ae%be%e5%a4%87%e6%97%a0%e6%b3%95%e8%a7%82%e7%9c%8bnetflix%e9%97%ae%e9%a2%98/)。
> 谢谢！

The Hosts feature of overture will simply solve your problem.

**Comment by newcoderlife** [comment]
> > 这个问题有一个类似的例子：netflix。
> > 它有A和AAAA两种解析，netflix会优先使用IPv6网络。在这种情况下无法通过透明代理来解锁netflix。（我尝试了IPv6的tproxy，它会暴露原始地址）。
> > 我们是否可以设置某些域名只返回A记录？比如像[这样](https://mengql12.wordpress.com/2019/03/05/openwrt%e7%94%a8shadowsocks%e8%bf%9e%e6%8e%a5%e6%97%b6%e7%bb%88%e7%ab%af%e8%ae%be%e5%a4%87%e6%97%a0%e6%b3%95%e8%a7%82%e7%9c%8bnetflix%e9%97%ae%e9%a2%98/)。
> > 谢谢！
> 
> The Hosts feature of overture could simply solve your problem.

By reading the source code, overture matches the ipv4 and ipv6 addresses in the hosts file separately, which can only block AAAA records.
Thanks for your reply!
