### ISSUE TITLE
How do I configure doh

### ISSUE THREAD

**Issue by thb007** [shawn1m/overture#214]
How to configure DOH? The document does not write DOH configuration!

**Comment by rampageX** [comment]
```
      {
        "Name": "Ali_HTTPS",
        "Address": "https://dns.alidns.com/dns-query",
        "Protocol": "https",
        "SOCKS5Address": "",
        "Timeout": 3,
        "EDNSClientSubnet": {
          "Policy": "auto",
          "ExternalIP": "223.73.56.110",
          "NoCookie": true
        }
      }
```

**Comment by thb007** [comment]
> ```
>       {
>         "Name": "Ali_HTTPS",
>         "Address": "https://dns.alidns.com/dns-query",
>         "Protocol": "https",
>         "SOCKS5Address": "",
>         "Timeout": 3,
>         "EDNSClientSubnet": {
>           "Policy": "auto",
>           "ExternalIP": "223.73.56.110",
>           "NoCookie": true
>         }
>       }
> ```

thanks
