### ISSUE TITLE
Google doh issue

### ISSUE THREAD

**Issue by Super-pixle** [shawn1m/overture#225]
使用https://dns.google/resolve ，overture一直提示Google-DNS Fail: dns: buffer size too small，DNSUpstream returned None answer，用浏览器打开https://dns.google/resolve?name=www.baidu.com ,可以发现解析是正常的，难道是因为https://dns.google/resolve 返回的content-type是application/x-javascript，导致overture出错吗？

**Comment by rampageX** [comment]
dns.google 需要使用代理。
