### ISSUE TITLE
1.6.1版本，TLS模式失效

### ISSUE THREAD

**Issue by pmkol** [shawn1m/overture#228]
"AlternativeDNS": [
    {
      "Name": "RubyfishDNS",
      "Address": "ea-dns.rubyfish.cn:853",
      "Protocol": "tcp-tls",
      "SOCKS5Address": "",
      "Timeout": 6,
      "EDNSClientSubnet": {
        "Policy": "disable",
        "ExternalIP": "",
        "NoCookie": true
      }
    }
  ],

配置文件填写如下，同样的配置文件，在1.6版本正常，1.6.1版本失效，不知道是BUG，还是新版本配置文件有变化？

**Comment by pmkol** [comment]
补充一下，失效的状态：

客户端nslookup访问DNS，
当为1.6版本可以返回结果，
当为1.6.1版本返回Server failed
报错为无法访问tls访问ea-dns.rubyfish.cn

**Comment by gaorui84** [comment]
同问，用Google和Cloudflare的DoT服务器无法解析报错如下：
WARN[2020-05-16 12:31:12] dns server address tcp-tls://dns.google:853 is invalid
WARN[2020-05-16 12:31:12] createTlsConn failed: dns up server address is invalid
WARN[2020-05-16 12:31:12] dns server address tcp-tls://one.one.one.one:853 is invalid
WARN[2020-05-16 12:31:12] createTlsConn failed: dns up server address is invalid

**Comment by rampageX** [comment]
```
      {
        "Name": "Google_Main",
        "Address": "dns.google:853@8.8.4.4",
        "Protocol": "tcp-tls",
        "SOCKS5Address": "",
        "Timeout": 6,
        "EDNSClientSubnet": {
          "Policy": "auto",
          "ExternalIP": "202.62.222.220",
          "NoCookie": true
        }
      },
```

**Comment by gaorui84** [comment]
这个配置经测试可用，但是要求DoT服务器端支持ECS，如果不用ECS就无法连接吗？（tcping 8.8.4.4 或 8.8.8.8 853正常）

**Comment by rampageX** [comment]
ECS 随便，可以关，关键是你要指定 dns.google 的 IP，要不谁来解析？ DoT/DoH 都有这个鸡生蛋蛋生鸡的问题。

**Comment by gaorui84** [comment]
之前试过不开ECS，地址填dns.google:853, 8.8.8.8:853或者dns.google:853@8.8.8.8好像都不行。
