### ISSUE TITLE
询问一个参数的使用

### ISSUE THREAD

**Issue by kimanlo** [shawn1m/overture#23]
请问
```
  "CacheSize" : 0
}
```
参数是如何使用的？

**Comment by shawn1m** [comment]
DNS 缓存的最大数量，数字为正时本地缓存开启，可以加速 DNS 查询。

**Comment by kimanlo** [comment]
我设置了数字，例如：4096，打开 -v 观察，看到乱码并且只显示一条解析就不再继续显示。

**Comment by shawn1m** [comment]
Windows CMD 的与 log 库之间的问题，目前没有很好的解决方法。
你可以打开 Cache 后用 dig 测试，可以看到效果（查询时间明显缩短）。

**Comment by kimanlo** [comment]
我就是在服务端的log那里看到有乱码和英文，然后在windows cmd 继续查询，服务端的log不会更新了。。。
我在服务器那里用pdnsd套overture，查询到的ip都是国外的，有没有更加好的办法？

**Comment by shawn1m** [comment]
可能是 pdnsd 在前面缓存了 DNS 记录，服务端直接用 overture 就好。

**Comment by kimanlo** [comment]
作者，你好，请问有没有打算log可以输出未txt格式文件呢？便于排查处理。

**Comment by shawn1m** [comment]
这个你可以考虑使用 supervisor 之类的工具实现，目前没有打算做在程序里。

**Comment by kimanlo** [comment]
好的，感谢作者的耐心回复！
打算向朋友推广这东西，不知作者来喝不喝茶的？ 🌚

**Comment by shawn1m** [comment]
DNS 方面的硬需求其实不多，这是一个开源项目，希望不要直接用于商业用途就好。
