### ISSUE TITLE
本地dns服务器不能设置成本机，否则解析域名时会出现死循环

### ISSUE THREAD

**Issue by gaorui84** [shawn1m/overture#234]
resolv.conf 不能设置 nameserver 127.0.0.1，否则解析域名时会不断出现Failed to connect to DNS upstream: dial tcp: i/o timeout形成死循环。

**Comment by shawn1m** [comment]
It's an dns over https or dns over tls common issue. 
IP address must be set directly if the system default nameserver is overture itself.
