### ISSUE TITLE
上游使用socks代理无法连接时会占用大量CPU/内存

### ISSUE THREAD

**Issue by fqx** [shawn1m/overture#235]
>  time="2020-05-28 19:33:16" level=warning msg="Failed to connect to DNS upstream: socks connect tcp 192.168.1.xx:xxxx->1.0.0.1:53: EOF"

我这台虚拟机上跑着pi-hole和overture，overture为pi-hole的上游DNS服务器。
最近出现过两次网络DNS故障，此虚拟机内存使用达到100%，CPU使用也100%。
日志里存在大量上述警告。

Debian Linux 4.19
overture 1.61
pi-hole 5.0

overture的AlternativeDNS除了用socks代理的，也有直接用tcp-tls的，不知道为什么卡在socks上面。

**Comment by fqx** [comment]
我怀疑1.61版有内存泄漏问题，运行几天之后overture的内存占用可以到200M左右，缓存DNS 5000条。

**Comment by rampageX** [comment]
内存泄漏很严重, VPS 上跑的 1.61 内存爆到 1G 多了,现在换 ts-dns 在用.

**Comment by fqx** [comment]
@rampageX 感谢，我也换ts-dns了

**Comment by sinnerliu** [comment]
> 内存泄漏很严重, VPS 上跑的 1.61 内存爆到 1G 多了,现在换 ts-dns 在用.

求科普ts-dns 是哪个工程呀，多谢

**Comment by rampageX** [comment]
@sinnerliu https://github.com/wolf-joe/ts-dns

**Comment by sinnerliu** [comment]
@rampageX 多谢，但是这个，不知道我配置的不对，还是怎么的，有个域名解析的ip不对，和overture有差异

**Comment by shawn1m** [comment]
Maybe that memory leak is related to the socks5, dns over tls or dns over https implementation. Luckily, I don't use any of them in my daily life and overture is stable as always.
Advanced users could try to use `host:port/debug/pprof/` (v1.7-rc1) to get some necessary information about memory when that problem occurs.
By the way, talk about other project and its detail configuration is not that relvant to this issue.
