### ISSUE TITLE
does it protect against ddos / dns poisoning / dns attack etc?

### ISSUE THREAD

**Issue by gitmko0** [shawn1m/overture#247]
sorry been a long time i touched dns stuff.
i'm looking at using it as a website hosting company, doing geoip based dns with this. 
1. does it protect against ddos / dns poisoning / dns attack etc?
2. is this production ready?
3. possible to expand to geo targeted ip dns?

4. any alternative using golang you recommend?
great software by the way

**Comment by shawn1m** [comment]
1. no.
2. From README: "Production usage is not recommended and there is no guarantee or warranty of it."
3. Expand IP by config file is possible, please try to read README first.
4. It depends on your needs, just google and try.
Thank you!

**Comment by LEXUGE** [comment]
For GeoIP, you could possibly take a look at a similar project that I have written. It offers you customized matching logic, including the usages of built-in geoip database.
https://github.com/LEXUGE/dcompass
