### ISSUE TITLE
优化 hosts 文件加载速度

### ISSUE THREAD

**Issue by lucifer9** [shawn1m/overture#27]
首先感谢作者，终于有了一个方便配置的可以替换 pdnsd 和 dnsmasq 组合的工具。不过使用过程中发现一个问题，我用于 adblock 等用途的 hosts 文件在 5 万行左右，这个时候在 rMBP 15-inch, Mid 2014 （2.2 GHz Intel Core i7）环境下启动 overture 需要将近一分钟；在 高通骁龙 820/821 环境下启动需要 3 到 4 分钟。不知这个速度是否还有优化的空间呢？谢谢！

**Comment by shawn1m** [comment]
目前的实现代码来自于 [go-dnsmasq](https://github.com/janeczku/go-dnsmasq) ，具体的细节未来我可以看看值得优化的地方，你可以把你用的 hosts 文件上传一下供测试。

**Comment by lucifer9** [comment]
感谢！
测试文件请看附件

[hosts.zip](https://github.com/shawn1m/overture/files/850007/hosts.zip)

**Comment by shawn1m** [comment]
d12271faf58d6fa2cbc7c17ead9fa3eae35c2ef3
并发读取分析 hosts 条目，测试你的 hosts，MacBook Pro (Retina, 13-inch, Early 2015) 大概 24s，i7-4790 的话 7s。你可以使用 -v，可以显示 hosts 读取的时间。

**Comment by lucifer9** [comment]
感谢！
实测 Mac 下面基本上启动以后立即可用。手机上还需要等 1 分钟不到才可用，不过已经没什么实际影响了。
