### ISSUE TITLE
对domainFile.Matcher参数不理解

### ISSUE THREAD

**Issue by Alion548** [shawn1m/overture#272]
domainFile.Matcher: Matching policy and implementation, including "full-list", "full-map", "regex-list", "mix-list", "suffix-tree" and "final". Default value is "full-map".

请问，比如我规则是：google.com，需要匹配a.google.com、bb.a.google.com，是不是需要suffix-tree参数？

**Comment by shawn1m** [comment]
Refer to: https://github.com/shawn1m/overture/issues/180
