### ISSUE TITLE
Verbose mode 下有部分字符乱码

### ISSUE THREAD

**Issue by sutcac** [shawn1m/overture#28]
非常好的软件！

终端显示汉字没有问题。

在配置文件中**开启缓存**，启动后查询dns，吐出信息如下：

```
DEBU[0005] XXX Answer: xxxx.xxx.xxx.      3600    IN      A       xxx.xxx.xxx.xxx
DEBU[0005] Try to match response ip address with IP network
DEBU[0005] IP network match fail, finally use alternative DNS
2U��`���] Cache    xxx.xxx.xxx.�9��^kK
```

**Comment by kimanlo** [comment]
Windows CMD 的与 log 库之间的问题，目前没有很好的解决方法。

via:  [./issues/23#issuecomment-285012131](https://github.com/shawn1m/overture/issues/23#issuecomment-285012131)

**Comment by shawn1m** [comment]
@kimanlo log 库处理一些 byte 数据有问题，干脆之间用字符串处理，已解决。
36b6d6f0bc50307fbed6af90f01fc1398a54f1f9
@sutcac
