### ISSUE TITLE
使用overture碰到的一个问题

### ISSUE THREAD

**Issue by shen09** [shawn1m/overture#30]
启动一段时间之后会出现如图所示的报错，导致overture直接结束进程。。不能解析。![qq 20170329134747](https://cloud.githubusercontent.com/assets/26760294/24441839/046fea48-148e-11e7-891a-cf032697a09b.jpg)

**Comment by maddie** [comment]
提供一下运行环境信息，以及配置文件内容

**Comment by shawn1m** [comment]
-v 运行，如果出现相同情况，请把 log 也一并放上来。
