### ISSUE TITLE
关于hosts通配符的建议和求助

### ISSUE THREAD

**Issue by lhwlhw** [shawn1m/overture#31]
首先我发现*.a.com好像不包括a.com？于是我就得写两行。然后发现当网址是c.b.a.com的时候，*.a.com也不能将其包括在内。不知道有没能把a.com结尾的全部指到一个IP的方法？目前我在搞FQ用的DNS，google家的东西域名非常多，如果能把google.com结尾的都指向一个IP（SNI IP）能节省大量空间并且更方便。还有google.xx这的域名，*放在后面似乎是没用的啊。如果已能实现，麻烦赐教。

**Comment by shawn1m** [comment]
hosts 的实现来自于 [go-dnsmasq](https://github.com/janeczku/go-dnsmasq) 
最初我只想要纯 hosts 的功能，但是他实现了通配符所以就一并放进来了。从我的角度看，hosts 本身就应该参照 hosts 的文件标准进行读取。对于你的问题，通配符逻辑我会做一些修改使得 *.a.com 包括 a.com，至于放在后面的情况目前不在考虑范围。

**Comment by lhwlhw** [comment]
谢谢回复。那么对于b.c.a.com或者d.c.b.a.com这样的，有没有办法做一个，比如**.a.com这样的通配符使得a.com结尾的全部包括？

**Comment by shawn1m** [comment]
可以修改一下相关实现把 **.a.com 放进来。

**Comment by m1911** [comment]
@shawn1m 这种方式多久能改好 不然添加域名太麻烦了

**Comment by lhwlhw** [comment]
干脆就直接*.a.com就全包括就好了，我想用到通配符的多半是这个目的

**Comment by shawn1m** [comment]
已包括 f9cc9f4872e0b955a656439c3b78bde4c147f495

**Comment by lhwlhw** [comment]
有没有办法做一个，比如**.a.com这样的通配符使得a.com结尾的全部包括？
请问这个还有没有计划啊？ @shawn1m
