### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by m1911** [shawn1m/overture#33]
./overture 运行起来了 关闭了ssh连接 overture也就没了 要怎么在后台运行？

**Comment by everfly** [comment]
可以通过使用`nohup`, `screep`等方式后台
具体使用可以参考https://www.ibm.com/developerworks/cn/linux/l-cn-nohup/

**Comment by m1911** [comment]
@everfly 在github 下载的自己编译需要什么样的环境？

**Comment by everfly** [comment]
@m1911 首先需要搭建好go语言环境，然后`go get -u github.com/shawn1m/overture/main`
最后可以利用源码里面的`build.py`自动编译
`python build.py`

**Comment by m1911** [comment]
@everfly 作者这个go 是什么版本的？还是什么版本都能进行编译？

**Comment by everfly** [comment]
go使用最新版本就好了，build.py编译生成的已经包含绝大多数环境

**Comment by m1911** [comment]
@everfly 打包编译好了新版本了 谢谢哈

**Comment by shawn1m** [comment]
我现在用的就是 go 1.8 具体使用的版本和依赖可以看 .travis.yml 文件。
