### ISSUE TITLE
1.3.4hosts文件有空行的话运行不了

### ISSUE THREAD

**Issue by lhwlhw** [shawn1m/overture#36]
windows版，386和amd64都这样。

如上面↑↑↑这样空行，就无法启动会一闪而过。
另外还有一个请求
请求就是之前的issue提到的，希望出一个以**.a.com包含全部a.com结尾域名(包括x.a.com;x.x.a.com;x.x.x.a.com......)的通配符。

**Comment by shawn1m** [comment]
1.3.4版本，我测试有空行没有问题，你可以把你的有问题的 hosts 提交一下；
目前 1.3.4 版本 *.a.com 已经包括了所有后缀是 a.com 的域名了，同时也包括 a.com 本身。

**Comment by shawn1m** [comment]
空行已修复，请测试 1.3.5-rc1

**Comment by lhwlhw** [comment]
@shawn1m 刚想上传给你的，谢谢你的及时修复。现在通配符用的特别爽，多亏了你们开发者的付出，谢谢！
