### ISSUE TITLE
不建议*全包括

### ISSUE THREAD

**Issue by aruisi2017** [shawn1m/overture#38]
之前由于通配符存在三级以上域名绕过hosts的问题，新版修正后将*.a.com中，.a之前的所有字符全包括了，由此就产生了一个问题。

当hosts写为*.ss0.bdstatic.com时，发现会把所有包含ss0字符的bdstatic.com域名全部指向到127.0.0.1，例如gss0.bdstatic.com

ss0.bdstatic.com是百度的广告域名，我要将其指向到127.0.0.1屏蔽掉，但gss0.bdstatic.com是百度知道的css一旦屏蔽导致百度知道无法正常访问。而这里面有不少是无需屏蔽的域名，此种方式误伤太大。

建议将*.ss0.bdstatic.com仅包括所有属于ss0.bdstatic.com这个域的子域，例如abc.ss0.bdstatic.com
而不扩展到包含ss0这个关键字的bdstatic.com的其他子域，例如abcss0.bdstatic.com

谢谢！

**Comment by shawn1m** [comment]
简单修改了一下，试一下 1.3.5-rc2
