### ISSUE TITLE
1.3.5-rc2运行时报错

### ISSUE THREAD

**Issue by aruisi2017** [shawn1m/overture#39]
time="2017-04-26T13:45:41+08:00" level=info msg="Overture 1.3.5-rc2"
time="2017-04-26T13:45:41+08:00" level=info msg="If you need any help, please visit the project repository: https://github.com/shawn1m/overture"
time="2017-04-26T13:45:41+08:00" level=fatal msg="Json syntex error: invalid character ':' after top-level value"
请问是什么原因？

**Comment by shawn1m** [comment]
检查一下你的配置文件是不是符合 json 格式吧
