### ISSUE TITLE
关于Windows release的一点疑问

### ISSUE THREAD

**Issue by lennox67** [shawn1m/overture#4]
现在的Windows版本程序似乎没法后台运行，
第几个版本会出最小化到托盘化～？

**Comment by holyshawn** [comment]
这个不在开发计划内，golang 主要还是写命令行程序，方便跨平台交叉编译。需要最小化托盘化的功能需要懂 Windows 界面编程的程序员来给 overture 包装一下，我这里就不做了。

**Comment by rwzsycwan** [comment]
写个脚本后台运行就成

**Comment by maddie** [comment]
@Matrikslee 建议用[nssm](https://nssm.cc/)之类的工具将overture作为Windows service运行

**Comment by Matrikslee** [comment]
@maddie 有时间我试试，谢谢～

**Comment by soarqin** [comment]
@Matrikslee go build时候加上-ldflags '-H windowsgui'，就可以不弹出命令行了，要杀程序的时候从任务管理器或者用tskill来杀

**Comment by shawn1m** [comment]
@everfly 这个主要还是考虑到用户的交互以及体验的问题。用 Go 编译形成的 noGUI 程序直接后台运行会没有任何直接信息反馈，程序运行状况未知，连退出都要任务管理器来杀，这会对用户形成很多的疑惑。当然，对于那些对程序运行有充分了解的人群，他们可以自己编译 noGUI 的版本自己用。对于正式的 Windows Release 而言，还是用原生 GUI 程序做个壳比较容易接受，退一步说，如 @maddie 所言，用nssm之类的工具将普通 exe 作为 Windows Service 来运行都比 noGUI 要可靠的多。
