### ISSUE TITLE
可否考虑降低cpu与带宽占用？

### ISSUE THREAD

**Issue by aruisi2017** [shawn1m/overture#41]
目前使用1.3.5-rc2版，与bind9.10做了简单对比发现cpu占用比bind高50%左右，带宽占用高出bind一倍。
dig返回的MSG SIZE包大小，比bind平均大2倍左右。
OnlyPrimaryDNS已设置为true
请问目前还有没有办法进一步降低cpu与带宽消耗呢？谢谢。

**Comment by shawn1m** [comment]
关掉 EDNS Client Subnet

**Comment by aruisi2017** [comment]
关闭EDNS后，对cdn是否就不友好了呢？

**Comment by shawn1m** [comment]
EDNS Client Subnet 的实现是基于 MSG 包中的  OPT 信息，必然会增大带宽。如果你用的 IP 就是你运行程序时的公网  IP，那么理论上开不开是一样的。

**Comment by aruisi2017** [comment]
请问对多核cpu是否有优化，负载能否均分到每个核心上？




发自网易邮箱大师
在2017年05月03日 10:48，Shawn 写道：

EDNS Client Subnet 的实现是基于 MSG 包中的 OPT 信息，必然会增大带宽。如果你用的 IP 就是你运行程序时的公网 IP，那么理论上开不开是一样的。

**Comment by shawn1m** [comment]
使用的是 golang 的 goroutine 处理单个请求，默认已经均衡在每个逻辑核心上了。
