### ISSUE TITLE
串联使用overture带不上客户端ip

### ISSUE THREAD

**Issue by aruisi2017** [shawn1m/overture#42]
之前在v2ex上提到过的问题：
c 是客户机， a 主机安装 overture ， b 主机也安装 overture ，然后 b 收到c的查询请求递归到 a ， a 再递归到 8.8.8.8或者119.29.29.29

此前您回复：如果开启 edns ，生效的应该都是 c 的公网出口 ip ；不开启的话，生效的是末端 a

今日测试发现，a和b都开启了edns，但客户端c接收到的解析结果是末端a主机ip递归到8.8.8.8或119.29.29.29的结果，在b向a的传递过程中，似乎将c客户端的ip丢失了。

**Comment by shawn1m** [comment]
请把你的配置文件和测试方式与结果提供一下。

**Comment by aruisi2017** [comment]
a主机是河南联通ip
b主机是上海电信ip
c客户端(thinkcenter)位于甘肃兰州电信
递归顺序是c>b>a>119.29.29.29
当c直接将www.163.com递归到a和b时，都能www.163.com位于甘肃兰州的cdn节点ip

c直接dig a主机，返回兰州ip
![a](https://cloud.githubusercontent.com/assets/27941320/25689283/41171baa-30b9-11e7-971b-41cb28bb36e0.jpg)

c直接dig b主机 返回兰州ip
![b](https://cloud.githubusercontent.com/assets/27941320/25689287/4e3c2352-30b9-11e7-9e83-ff71d819beea.jpg)

a主机配置文件
![a](https://cloud.githubusercontent.com/assets/27941320/25689291/54b4f510-30b9-11e7-8de8-029ef712df16.jpg)

b主机配置文件
![b a](https://cloud.githubusercontent.com/assets/27941320/25689292/586bd390-30b9-11e7-936a-53701c54ce26.jpg)

当将b主机递归到a主机后，客户端c dig 163得到的ip位于浙江电信，不再是甘肃兰州了，也就是说a主机将b主机的ip当做了客户端ip做了返回。在传递过程中，丢失了c客户端的ip.
![b a c](https://cloud.githubusercontent.com/assets/27941320/25689294/5ce935ca-30b9-11e7-8d34-2c0efcf19678.jpg)

**Comment by shawn1m** [comment]
简单修改了一下逻辑，你可以试试 1.3.5-rc3 版本，我这里没有你的测试环境，你自行测试吧。

**Comment by aruisi2017** [comment]
1.3.5-rc3 版本基本解决了此问题。但又发现，将a主机和b主机的位置对换后，即c>a>b>119.29.29.29，出现解析结果混乱的情况，解析得到的ip在全国范围内乱跳，进一步排查发现这是因为a主机为bgp多线主机（联通电信移动同时接入），而b主机是电信单线接入。

现在的情况是：
1.当bgp线路主机安装overture后可以给后面安装了overture的单线b主机正确返回客户端c的ip

2.单线b主机安装overture后无法给后面安装了overture的bgp线路主机正确返回客户端c的ip

也就是说问题出在bgp线路的主机上，我使用阿里云、腾讯云、百度云这些bgp主机做了测试均存在此问题。此外接#43问题，我发现所有的bgp主机运行overture后均会在日志中出现大量warning msg="Maybe DNSPod Fail: does not support edns client subnet and it need to be replaced"错误（1.3.5-rc3同样存在），所有的单线主机均无此问题。

![default](https://cloud.githubusercontent.com/assets/27941320/25747204/3bbca442-31d9-11e7-81b8-dac7777c5061.JPG)


为了方便您进一步排查此问题，可否留个私人邮件地址，我给您两台临时测试主机方便您进一步排查问题。

**Comment by aruisi2017** [comment]
您好，经反复排查测试，此问题已确认是由缓存造成的，当a主机、b主机都关闭缓存时，此问题消失，当有任何一台主机开启缓存时即出现ip乱跳的情况。推测是由于bgp多线主机能分别从上层overture分别获得多个线路对应的解析ip存在缓存里，再向客户端传递时从而造成缓存读取混乱。当关闭缓存功能后DNSPod Fail: does not support edns client subnet and it need to be replaced此错误消失。

**Comment by aruisi2017** [comment]
发现一个新问题：
c>b>a>119.29.29.29这样使用时，会有部分二三级域名无法解析，例如imgcache.qq.com
dig 返回
;; connection timed out; no servers could be reached

此时日志显示
warning msg="DNSPod Fail: Maybe this server does not support EDNS Client Subnet"

**Comment by shawn1m** [comment]
缓存逻辑的确有一些问题，我找时间修改。新问题报错原因和 #43 是一致的，我推测是因为由于多次传递，有一些数据包可能会丢失或者产生很大的延迟。

**Comment by aruisi2017** [comment]
是的，经过两次overture后即便是同地域的两台主机dig延迟也会达到300ms以上。另，若您需要临时测试主机，我可以提供您测试。




发自网易邮箱大师
在2017年05月08日 18:28，Shawn 写道：

缓存逻辑的确有一些问题，我找时间修改。新问题报错原因和 #43 是一致的，我推测是因为由于多次传递，有一些数据包可能会丢失或者产生很大的延迟。
