### ISSUE TITLE
warning msg="Maybe DNSPod Fail: does not support edns client subnet and it need to be replaced"

### ISSUE THREAD

**Issue by aruisi2017** [shawn1m/overture#43]
运行后过了几小时日志里出现错误：
time="2017-05-04T10:38:45+08:00" level=info msg="Start overture on :53"
time="2017-05-04T12:20:45+08:00" level=warning msg="Maybe DNSPod Fail: does not support edns client subnet and it need to be replaced"
time="2017-05-04T15:23:42+08:00" level=warning msg="Maybe DNSPod Fail: does not support edns client subnet and it need to be replaced"

然后又过了两小时，overture进程无故自己退出了，内存并没有占用完。

**Comment by shawn1m** [comment]
试试 1.3.5-rc3 版本，你这种情况十分异常，可能是 edns 传递时出现的问题，或者是网络方面的问题。
触发了以下错误：
ErrTruncated indicates that we failed to unpack a truncated message. We unpacked as much as we had so Msg can still be used, if desired
