### ISSUE TITLE
三重错误

### ISSUE THREAD

**Issue by aruisi2017** [shawn1m/overture#46]
1.3.5-rc4版本
运行方式：c>b>a>dnspod （c为客户端，b为第2台overture a为第一台overture ）
运行后不久，a报错：
level=warning msg="Dial DNS upstream failed: dial udp 119.29.29.29:53: socket: too many open files"
level=warning msg="DNSPod Fail: Maybe this server does not support EDNS Client Subnet"

b报错：
level=warning msg="DNSPod Fail: Send question message failed"

dig @b主机 imgcache.qq.com无响应。

**Comment by shawn1m** [comment]
这应该是你的socket数量超限导致的，参见：
https://stackoverflow.com/questions/32325343/go-tcp-too-many-open-files-debug

**Comment by aruisi2017** [comment]
1.socket数量超限问题已解决。
2.第2个错误已确认是119.29.29.29前几日受到攻击不稳定所致。
3.第三个问题在升级到1.3.5-rc5版本后，b主机日志仍然存在level=warning msg="DNSPod Fail: Send question message failed"
且不知什么原因，一旦两台overture串联使用，imgcache.qq.com就会无法解析，不知这种域名的解析是否比较特殊？

**Comment by aruisi2017** [comment]
imgcache.qq.com无法解析的情况出现在当将PrimaryDNS设置为119.29.29.29或者119.28.28.28时出现，如果将PrimaryDNS设置为8.8.8.8则可以解析imgcache.qq.com，但是8.8.8.8似乎和overture之间无法使用edns。

**Comment by aruisi2017** [comment]
8.8.8.8若要得到EDNS支持需向Google public DNS提交白名单申请，直接在配置文件中填写8.8.8.8无效。
目前主要问题就是imgcache.qq.com这类域名在用dnspod时串联无法解析。

**Comment by shawn1m** [comment]
level=warning msg="DNSPod Fail: Send question message failed"
指的是 DNS 请求发送不成功，这是十分正常的现象，丢包之类的都会导致这种情况，仅仅只是 warning 不影响程序运行。
至于 imgcache.qq.com 这个域名我猜测是 119.29.29.29 服务端的策略问题，毕竟其他域名都完全正常。

**Comment by aruisi2017** [comment]
感谢耐心解答，可能是DNSpod近期持续被攻击造成网络波动的原因导致报错。
至于imgcache.qq.com的问题，单台overture指向119.29.29.29无问题可以返回解析结果，两台串联后就拒绝解析了，不明所以。至于8.8.8.8带不上用户源ip。谢~

**Comment by aruisi2017** [comment]
1.3.5正式版
dig时偶发错误Warning: ID mismatch: expected ID 977, got 7986，时而能解析时而不能解析。

**Comment by shawn1m** [comment]
请把在这种情况下的 verbose 信息以及相关配置文件提供一下，解析的域名是来自于 hosts 的还是远端的？

**Comment by kdrx** [comment]
1.3.5正式版
dig 出现ID mismatch错误。
观察log，发现正式版对于命中domains文件中的域名时候，和rc5的处理方法不同，rc5直接交给alternative DNS，并最终返回ip。而正式版则是同时对所有dns 服务起发起查询，有时返回超时。

**Comment by shawn1m** [comment]
@kdrx 能不能提供一下 dig 的内容以及 mismatch 再现的方法?
正式版改进了查询逻辑，在所有判断之前尝试查询 PrimaryDNS 和 AlternativeDNS 的结果以提升速度，仍有优化空间。

**Comment by aruisi2017** [comment]
1.35正式版两台无法串联使用，在较大流量下，前面的一台主机会只接受解析请求包，不返回或者只返回十分之一左右的包，导致出现大量mismatch错误。之前版本在串联使用时仅仅是返回的ip不准确，1.35是直接没法串联使用。
另，根据google官方解释，8.8.8.8似乎不能保证接受客户端传递的ECS头，google官方建议通过httpdns传递以确保准确。详见https://groups.google.com/forum/#!topic/public-dns-discuss/nuQZcMVhcoo

**Comment by shawn1m** [comment]
有一个逻辑优化在 1.3.5.1 版本，可能可以略微改善性能。
mismatch 不是由没有包返回导致的，我这里没有发生这种情况，我需要 mismatch 能够重现我才能调试出 bug 所在，如需稳定可以暂时先使用 rc5 版本。
根据你的信息，我把 README 中 8.8.8.8 的支持提示去掉了，DNS over HTTPS 应该已经有了相关实现，如果你需要与 overture 结合使用的话直接套用即可，overture 目前没有支持 DNS over HTTPS 的打算。

**Comment by shawn1m** [comment]
同 #51 。
