### ISSUE TITLE
请问一下这个怎么和shadowsocks配和使用呢，ss安卓内置overture吗？电脑端怎么实现呢

### ISSUE THREAD

**Issue by sosmygirl** [shawn1m/overture#49]
请问一下这个怎么和shadowsocks配和使用呢，我看本地和服务端都有人部署，，有人能说一下使用方法没谢谢

>  听说overture的cdn解析特牛逼

补充一下我的想法： 
user访问请求——>overture dns查询（或路由缓存 ）——>ip（国外）——>shadowsocks
............................................ .........................................................................  ip（国内）——>直连

**Comment by shawn1m** [comment]
根据 #14 ，安卓版作者已经在他的软件中引入了 overture，具体用于何处我没有关注。
overture 的 cdn 解析是建立于 DNSPod 对  EDNS Client Subnet 的支持之上，对需要搭建面向公网的 DNS 服务器比较有意义，对于一般用户意义不大，因为 DNSPod 默认采用的都是当前用户的公网 IP。
至于你的想法，应该是 IP 分流，你可以自己 Google 相关结果，项目的 issue 还是讨论项目本身的问题为好。

**Comment by sosmygirl** [comment]
谢谢，大概了解了
