### ISSUE TITLE
请求添加"默认服务器"字段

### ISSUE THREAD

**Issue by plain-face** [shawn1m/overture#54]
$ nslookup - 119.29.29.29
默认服务器:  pdns.dnspod.cn
Address:  119.29.29.29

$ nslookup - 223.5.5.5
默认服务器:  public1.alidns.com
Address:  223.5.5.5
使用nslookup命令时，一般的公网DNS都会返回'默认服务器'字段

$ nslookup - 192.168.10.251（overture的地址）
默认服务器:  UnKnown
Address:  192.168.10.251
使用overture服务器时，此字段返回UnKnown
是否可以自己定义？

**Comment by shawn1m** [comment]
这个默认服务器的值是  DNS IP 通过 rDNS 查询 PTR 记录得到的结果，除非中间劫持并伪造 PTR 记录否则不可定义。overture 原则上应尽量少的对 DNS 报文进行修改，这种伪造记录的行为显然是无法支持的。

不过，如果自用的话，可以参考下文的方法：
http://www.randika.info/2013/01/how-to-fix-nslookup-default-server.html
