### ISSUE TITLE
1.35.1有时解析很慢，dig返回mismatch的简单分析。

### ISSUE THREAD

**Issue by kdrx** [shawn1m/overture#56]
对于1.35.1和1.35-rc5
在不缓存的情况下，分别用dig 请求解析twitter.com和v2ex.com的日志。

1.35.1
time="2017-07-11T15:24:28+08:00" level=debug msg="Question: ;v2ex.com.  IN   A"
time="2017-07-11T15:24:28+08:00" level=debug msg="Matched: Custom domain v2ex.com v2ex.com"
time="2017-07-11T15:24:28+08:00" level=debug msg="DNSTunnel Answer: v2ex.com. 1799  IN  A 23.251.125.131"
time="2017-07-11T15:24:28+08:00" level=debug msg="DNSTunnel Answer: v2ex.com. 1799  IN  A 23.251.124.131"
time="2017-07-11T15:24:28+08:00" level=debug msg="DNSTunnel Answer: v2ex.com. 1799  IN  A 23.251.126.133"
time="2017-07-11T15:24:33+08:00" level=debug msg="Question: ;v2ex.com.  IN   A"
time="2017-07-11T15:24:33+08:00" level=debug msg="Matched: Custom domain v2ex.com v2ex.com"
time="2017-07-11T15:24:33+08:00" level=debug msg="DNSTunnel Answer: v2ex.com. 1799  IN  A 23.251.125.131"
time="2017-07-11T15:24:33+08:00" level=debug msg="DNSTunnel Answer: v2ex.com. 1799  IN  A 23.251.124.131"
time="2017-07-11T15:24:33+08:00" level=debug msg="DNSTunnel Answer: v2ex.com. 1799  IN  A 23.251.126.133"
time="2017-07-11T15:24:33+08:00" level=debug msg="Cached: v2ex.com. 1 "
我只dig一次返回，而日志里面却向上游服务器发送了两次请求，dig这边显示：
Warning: ID mismatch: expected ID 34457, got 39936
Warning: ID mismatch: expected ID 34457, got 6752
过了10秒钟后才返回ip。

1.35-rc5
time="2017-07-11T15:18:28+08:00" level=debug msg="Question: ;v2ex.com.  IN   A"
time="2017-07-11T15:18:28+08:00" level=debug msg="Matched: Custom domain v2ex.com v2ex.com"
time="2017-07-11T15:18:28+08:00" level=debug msg="DNSTunnel Answer: v2ex.com. 1413  IN  A 23.251.124.131"
time="2017-07-11T15:18:28+08:00" level=debug msg="DNSTunnel Answer: v2ex.com. 1413  IN  A 23.251.126.133"
time="2017-07-11T15:18:28+08:00" level=debug msg="DNSTunnel Answer: v2ex.com. 1413  IN  A 23.251.125.131"
time="2017-07-11T15:18:28+08:00" level=debug msg="Cached: v2ex.com. 1 "
这种也是dig一次，日志也是请求一次，返回正常，dig迅速返回ip。

1.35.1
time="2017-07-11T15:18:38+08:00" level=debug msg="Question: ;twitter.com. IN   A"
time="2017-07-11T15:18:38+08:00" level=debug msg="Matched: Custom domain twitter.com twitter.com"
time="2017-07-11T15:18:38+08:00" level=debug msg="DNSTunnel Answer: twitter.com.  1513  IN  A 104.244.42.1"
time="2017-07-11T15:18:38+08:00" level=debug msg="DNSTunnel Answer: twitter.com.  1513  IN  A 104.244.42.193"
time="2017-07-11T15:18:38+08:00" level=debug msg="Cached: twitter.com. 1 "
正常，dig迅速返回ip。

1.35-rc5
time="2017-07-11T15:24:22+08:00" level=debug msg="Question: ;twitter.com. IN   A"
time="2017-07-11T15:24:22+08:00" level=debug msg="Matched: Custom domain twitter.com twitter.com"
time="2017-07-11T15:24:22+08:00" level=debug msg="DNSTunnel Answer: twitter.com.  1450  IN  A 104.244.42.129"
time="2017-07-11T15:24:22+08:00" level=debug msg="DNSTunnel Answer: twitter.com.  1450  IN  A 104.244.42.1"
time="2017-07-11T15:24:22+08:00" level=debug msg="Cached: twitter.com. 1 "
正常，dig迅速返回ip。

总结就是，rc5版只会发送一次请求，等待上游服务器返回请求值后再返回给下游。
而1.35.1不知道基于什么判断会有时（并不是所有情况下都这样）连续发送两次请求给上游服务器，而且两次都有返回，dig这边就观察到了这种warning

**Comment by kdrx** [comment]
1.35-rc5版一切正常，1.35.1有时会解析不成功，希望能改进下。

**Comment by shawn1m** [comment]
dig向上游服务器发送两次请求应该是超时导致的。目前同时进行 PrimaryDNS 和 AlternativeDNS 查询存在很多问题，已经在1.3.5.2中改成 rc5的顺序查询了。

**Comment by kdrx** [comment]
嗯，已解决。
