### ISSUE TITLE
有关AAAA记录转发5S超时的bug

### ISSUE THREAD

**Issue by robinwangrubin** [shawn1m/overture#58]
hi 你好
我在使用你的ot之后遇到了如下的问题；想咨询您一下；细节如下：

oveture（192.168.1.1）配置主DNS是内网的一台主DNS服务器（192.168.1.2）；overture的备NDS 也是内网的一台备DNS（192.168.1.3）；客户端DNS指向overture（192.168.1.1）之后；A记录解析没问题；AAAA记录5s超时； 客户端直接将DNS指向内网的主或备DNS；没有此问题。

下面是同过overture之后超时的现象
![image](https://user-images.githubusercontent.com/24934186/28766536-98d4bc24-7602-11e7-8e5e-a410cb6ac141.png)

下面是直接指向内网DNS的现象
![image](https://user-images.githubusercontent.com/24934186/28768266-89033bb6-7609-11e7-9b01-2df417a28e88.png)

![image](https://user-images.githubusercontent.com/24934186/28768892-f53700cc-760b-11e7-8c1d-18a1b97f7187.png)

-----------------------------------

> curl 默认会查询AAAA记录；curl 通过overture之后；全部出现5s超时的问题；求解答~~

### 配置文件如下
{
"BindAddress": ":53",
"PrimaryDNS": [
{
"Name": "DNSPod",
"Address": "192.168.1.2:53",
"Protocol": "udp",
"SOCKS5Address": "",
"Timeout": 6,
"EDNSClientSubnet": {
"Policy": "disable",
"ExternalIP": ""
}
}
],
"AlternativeDNS": [
{
"Name": "OpenDNS",
"Address": "192.168.1.3:53",
"Protocol": "udp",
"SOCKS5Address": "",
"Timeout": 2,
"EDNSClientSubnet": {
"Policy": "disable",
"ExternalIP": ""
}
}
],
"OnlyPrimaryDNS": false,
"RedirectIPv6Record": true,
"IPNetworkFile": "./ip_network_sample",
"DomainFile": "./domain_sample",
"DomainBase64Decode": true,
"HostsFile": "./hosts_sample",
"MinimumTTL": 0,
"CacheSize" : 0,
"RejectQtype": [255]
}

----------------------------

### 日志如下

`time="2017-07-31T15:41:49+08:00" level=info msg="Overture 1.3.5.2"
time="2017-07-31T15:41:49+08:00" level=info msg="If you need any help, please visit the project repository: https://github.com/shawn1m/overture"
time="2017-07-31T15:41:49+08:00" level=info msg="Load IP network file successful"
time="2017-07-31T15:41:49+08:00" level=info msg="Load domain file successful"
time="2017-07-31T15:41:49+08:00" level=info msg="Minimum TTL is disabled"
time="2017-07-31T15:41:49+08:00" level=info msg="Cache is disabled"
time="2017-07-31T15:41:49+08:00" level=debug msg="Load hosts took 287ns"
time="2017-07-31T15:41:49+08:00" level=info msg="Load hosts file successful"
time="2017-07-31T15:41:49+08:00" level=info msg="Start overture on :53"

time="2017-07-31T15:53:51+08:00" level=debug msg="Question: ;thirdapi.xxxxx.com.\tIN\t A"
time="2017-07-31T15:53:51+08:00" level=debug msg="Domain match fail, try to use primary DNS"
time="2017-07-31T15:53:51+08:00" level=debug msg="Question: ;thirdapi.xxxxx.com.\tIN\t AAAA"
time="2017-07-31T15:53:51+08:00" level=debug msg="Finally use alternative DNS"
time="2017-07-31T15:53:51+08:00" level=debug msg="DNSPod Answer: thirdapi.xxxxx.com.\t86400\tIN\tA\t10.199.1.11"
time="2017-07-31T15:53:51+08:00" level=debug msg="Primary DNS answer is empty, finally use alternative DNS"
time="2017-07-31T15:53:56+08:00" level=debug msg="Question: ;thirdapi.xxxxx.com.\tIN\t A"
time="2017-07-31T15:53:56+08:00" level=debug msg="Domain match fail, try to use primary DNS"
time="2017-07-31T15:53:56+08:00" level=debug msg="DNSPod Answer: thirdapi.xxxxx.com.\t86400\tIN\tA\t10.199.1.11"
time="2017-07-31T15:53:56+08:00" level=debug msg="Try to match response ip address with IP network"
time="2017-07-31T15:53:56+08:00" level=debug msg="Matched: IP network 10.199.1.11 0.0.0.0/0"
time="2017-07-31T15:53:56+08:00" level=debug msg="Finally use primary DNS"
time="2017-07-31T15:53:56+08:00" level=debug msg="Question: ;thirdapi.xxxxx.com.\tIN\t AAAA"
time="2017-07-31T15:53:56+08:00" level=debug msg="Finally use alternative DNS"`

--------------------------

Note: 由于dig和nslookup只会解析A记录；所以非常快；没有遇到此问题。但是CURL默认会解析4A记录；造成IPV6转发超时的现象。

**Comment by robinwangrubin** [comment]
## 需求描述

---------------------

* 客户端DNS指向voerture
* overture优先找PrimaryDNS（我的内网DNS解析）
* PrimaryDNS无法解析找AlternativeDNS（公网DNS解析）

> 原因: 有些棕的域名；内网没有配置；但是公网有；想要实现如果内网有就返回内网IP， 如果内网没有就去公网DNS查询一遍。

**Comment by robinwangrubin** [comment]
这个是直接指向我的内网服务器；非常快。 通过ot代理后就会出现5s超时了
、
![image](https://user-images.githubusercontent.com/24934186/28767320-c6750866-7605-11e7-87f1-7cdee33cbbc1.png)

**Comment by robinwangrubin** [comment]
[root@Centos6 overture]# tail -f overture.log 
time="2017-07-31T15:37:02+08:00" level=info msg="Overture 1.3.5.2" 
time="2017-07-31T15:37:02+08:00" level=info msg="If you need any help, please visit the project repository: https://github.com/shawn1m/overture" 
time="2017-07-31T15:37:02+08:00" level=error msg="Open IP network file failed: open : no such file or directory" 
time="2017-07-31T15:37:02+08:00" level=error msg="Open Custom domain file failed: open : no such file or directory" 
time="2017-07-31T15:37:02+08:00" level=info msg="Minimum TTL is disabled" 
time="2017-07-31T15:37:02+08:00" level=info msg="Cache is disabled" 
time="2017-07-31T15:37:02+08:00" level=info msg="Load hosts file successful" 
time="2017-07-31T15:37:02+08:00" level=info msg="Start overture on :53"
time="2017-07-31T15:37:45+08:00" level=debug msg="Question: ;thirdapi.wandafilm.com.\tIN\t A" 
time="2017-07-31T15:37:45+08:00" level=debug msg="Domain match fail, try to use primary DNS" 
time="2017-07-31T15:37:45+08:00" level=debug msg="Question: ;thirdapi.wandafilm.com.\tIN\t AAAA" 
time="2017-07-31T15:37:45+08:00" level=debug msg="Finally use alternative DNS" 
time="2017-07-31T15:37:45+08:00" level=debug msg="DNSPod Answer: thirdapi.wandafilm.com.\t86400\tIN\tA\t10.199.1.11" 
time="2017-07-31T15:37:45+08:00" level=debug msg="Primary DNS answer is empty, finally use alternative DNS" 
time="2017-07-31T15:37:50+08:00" level=debug msg="Question: ;thirdapi.wandafilm.com.\tIN\t A" 
time="2017-07-31T15:37:50+08:00" level=debug msg="Domain match fail, try to use primary DNS" 
time="2017-07-31T15:37:50+08:00" level=debug msg="DNSPod Answer: thirdapi.wandafilm.com.\t86400\tIN\tA\t10.199.1.11" 
time="2017-07-31T15:37:50+08:00" level=debug msg="Try to match response ip address with IP network" 
time="2017-07-31T15:37:50+08:00" level=debug msg="IP network match fail, finally use alternative DNS" 
time="2017-07-31T15:37:50+08:00" level=debug msg="OpenDNS Answer: thirdapi.wandafilm.com.\t86400\tIN\tA\t10.199.1.11" 
time="2017-07-31T15:37:50+08:00" level=debug msg="Question: ;thirdapi.wandafilm.com.\tIN\t AAAA" 
time="2017-07-31T15:37:50+08:00" level=debug msg="Finally use alternative DNS"

**Comment by robinwangrubin** [comment]
[root@Centos6 overture]# cat config.json 
{
  "BindAddress": ":53",
  "PrimaryDNS": [
    {
      "Name": "DNSPod",
      "Address": "192.168.50.251:53",
      "Protocol": "udp",
      "SOCKS5Address": "",
      "Timeout": 6,
      "EDNSClientSubnet": {
        "Policy": "disable",
        "ExternalIP": ""
      }
    }
  ],
  "AlternativeDNS": [
    {
      "Name": "OpenDNS",
      "Address": "192.168.50.252:53",
      "Protocol": "udp",
      "SOCKS5Address": "",
      "Timeout": 2,
      "EDNSClientSubnet": {
        "Policy": "disable",
        "ExternalIP": ""
      }
    }
  ],
  "OnlyPrimaryDNS": false,
  "RedirectIPv6Record": true,
  "IPNetworkFile": "./ip_network_sample",
  "DomainFile": "./domain_sample",
  "DomainBase64Decode": true,
  "HostsFile": "./hosts_sample",
  "MinimumTTL": 0,
  "CacheSize" : 0,
  "RejectQtype": [255]
}

**Comment by shawn1m** [comment]
如果请求的“thirdapi.xxxxx.com”域名本身不带 AAAA 记录，overture 会等待设定的超时时间后再返回。

**Comment by shawn1m** [comment]
```
> time curl -I bt.neu6.edu.cn

HTTP/1.1 301 Moved Permanently
Date: Fri, 04 Aug 2017 11:25:38 GMT
Server: Apache/2.2.15 (CentOS)
X-Powered-By: PHP/5.4.45
location: forum.php
Content-Type: text/html

curl -I bt.neu6.edu.cn  0.01s user 0.01s system 0% cpu 1.625 total
```

我选择了一个 AAAA 实际域名测试，如果正常返回的话也就 1s 多，你的情况应该比较特殊，等我有时间会好好考虑，目前你可以设置一定的 CacheSize 规避这个问题。

**Comment by robinwangrubin** [comment]
@shawn1m 嗯嗯我们域名实际上都没有配置4A记录的；但是real dns会直接返回空值；然后通过ot就会一直等待5s； 开启了cachesize 也无法规避这个问题；

**Comment by robinwangrubin** [comment]
@shawn1m 
这是我通过代理访问百度的情况
![image](https://user-images.githubusercontent.com/24934186/29011422-8e31e252-7b65-11e7-9565-b38b633b8e0b.png)

---------------
这是我直接指向114DNS的情况
![image](https://user-images.githubusercontent.com/24934186/29011441-af6a47b6-7b65-11e7-9fc5-ddc2c5e60205.png)

**Comment by robinwangrubin** [comment]
@shawn1m  你可以参考这篇文档 
> http://coolnull.com/3820.html 
 
原因应该是ot处理网络请求的缘故

**Comment by robinwangrubin** [comment]
## 你好我通过抓包发现问题的原因了；的确是OT在转发4A记录的时候转发了错误的包导致。 ## 

抓包过程分析如下：

------------------------------

客户端（169.220） 通过 OT代理（0.3）访问域名；主DNS 114 备DNS 180

-----------------------------------
> 客户端发送了一个A记录[0x380e]解析请求和一个4A[0x9a24]记录解析请求 到 OT ；这一步没问题。

![image](https://user-images.githubusercontent.com/24934186/29160529-2a761e36-7de5-11e7-993c-f80ecdeee9da.png)

-------------------------------------

> OT 将4A[0x9a24]记录转发给备DNS 180。 将A记录[0x380e]转发给主DNS 114。 这一步没问题。

![image](https://user-images.githubusercontent.com/24934186/29160721-fb330fc0-7de5-11e7-9750-8961c7e0a2a1.png)

-----------------------------------------------

> 114返回 A记录[0x380e] 给OT OT 返回A记录[0x380e]给客户端；这一步没问题。

![image](https://user-images.githubusercontent.com/24934186/29160811-4ef4d1fc-7de6-11e7-84cf-35531d2e04c9.png)

------------------------------------

> 180返回4A[0x9a24]空记录给OT；OT却转发给A记录[0x380e]给客户端；这一步转发包错误！！！

![image](https://user-images.githubusercontent.com/24934186/29161445-d8f08d9a-7de8-11e7-970e-a1ded4735424.png)

--------------------------------------

> 5s客户端等待超时；重新发起A记录请求给OT；ok

**Comment by shawn1m** [comment]
修复了一个并发安全的 bug，你可以试试新版本是否已经解决问题。

**Comment by robinwangrubin** [comment]
@shawn1m 亲测已经解决此问题；请问问题出现的具体原因是什么？我之前的抓包分析是否正确？

**Comment by shawn1m** [comment]
并发方面的问题，数据结构没有分离好，在快速连续查询时有可能会出现。
