### ISSUE TITLE
如何统计独立的IP数量

### ISSUE THREAD

**Issue by ponyxx** [shawn1m/overture#59]
如何才能统计独立的IP数量，这样可以方便分析DNS的使用量

**Comment by shawn1m** [comment]
可能未来可以在 verbose 模式里加入源 IP 的显示，不太会专门为此做统计。

**Comment by ponyxx** [comment]
好，期待

**Comment by robinwangrubin** [comment]
@shawn1m 你好请问一下 linux上AAAA记录转发超时问题；会在下个版本更新么~~

**Comment by shawn1m** [comment]
1.3.6rc2 已实现源 IP 显示。
