### ISSUE TITLE
请教几个问题

### ISSUE THREAD

**Issue by tec1987** [shawn1m/overture#67]
看了说明文档，有几个问题请教一下:

如果我在配置文件中将主DNS配置为ISP的DNS，用来解析大部分解析没问题的域名
将备用DNS配置为防污染的DNS，用来解析一些被污染的域名
那么我该在哪里配置这个黑名单（被污染的域名）

对于"Policy"配置：
disable 说明禁用ECS功能，转发DNS查询时不提交ECS，此时ExternalIP配置不起作用；
auto 如果客户端IP为公网IP时（来自外网查询）将此客户端IP作为ECS提交，
如果客户端IP为私网IP时（来自内网的查询）将本地外网IP作为ECS提交；
以上理解是否正确？
如果Policy 配置为auto 同时配置了ExternalIP: 'x.x.x.x' 程序是如何逻辑处理的？

IPNetworkFile、DomainFile、HostsFile
这三个文件的具体作用，程序逻辑是怎样处理的，能否给个示列说明一下？

**Comment by kimanlo** [comment]
当Policy设置为auto的时候就使用Externa lIP来实现ECS。

IPNetworkFile 就是用主DNS解析得出的IP不在其中就使用备用DNS解析；
DomainFile 就是被污染的域名列表，默认使用Base6464加密的GFWLIST；
HostsFile 就是和Windows host文件一样的功能。

**Comment by tec1987** [comment]
@kimanlo
好的，谢谢解答

**Comment by tec1987** [comment]
看了下V2，基本上明白了，可以关了

主题为什么无法编辑，点编辑没有任何反应

**Comment by shawn1m** [comment]
这些内容在 README 中都有说明，你的理解是正确的。
