### ISSUE TITLE
你好，想请教下,已经安装完成DNSPod 使用UDP但总是报错

### ISSUE THREAD

**Issue by tudi1909** [shawn1m/overture#69]
内容如下：
问题
1.DNSPod Fail: Response message is nil, maybe timeout, please check your query or dns configuration
2.Dial DNS upstream failed: dial tcp 119.29.29.29:53: getsockopt: connection refused 

也没有做什么改动也不知道为何这样？
改为TCP协议即可正常 问题1已没有出现问题，单随后出现了问题2，我将DNSPod改为了阿里的DNS，正常！

**Comment by shawn1m** [comment]
可能是你自身网络环境或者 DNSPod 的问题如果阿里 DNS 正常的话。

**Comment by tudi1909** [comment]
好，我还以为程序有什么问题，感谢回复，那我就切到TCP下面用

**Comment by 1258159678** [comment]
dnspod不支持tcp的
