### ISSUE TITLE
让域名返回指定ip

### ISSUE THREAD

**Issue by m1911** [shawn1m/overture#7]
如何配置让域名返回指定ip 就像dnsmasq那样

**Comment by holyshawn** [comment]
目前还没有开发这个功能的计划，你可以在 overture 的外面套一层 dnsmasq 实现。

**Comment by holyshawn** [comment]
@freeyoung 新版本已支持。

**Comment by m1911** [comment]
"IPNetworkFile": "/path/to/ip_network_file",
  "DomainFile": "/path/to/domain_file",
  "DomainBase64Decode": true,
  "HostsFile": "/path/to/hosts_file",

在这个地方配置的？

**Comment by m1911** [comment]
"IPNetworkFile": "/path/to/ip_network_file",
  "DomainFile": "/path/to/domain_file",
  "DomainBase64Decode": true,
  "HostsFile": "/path/to/hosts_file",
在这个地方配置的？
@holyshawn

**Comment by holyshawn** [comment]
@m1911 HostsFile

**Comment by m1911** [comment]
@holyshawn 可以泛解析？

**Comment by holyshawn** [comment]
@m1911 简单的泛解析，请先看 README：
Using wildcard * in the subdomain for wildcard matching is allowed, e.g. 192.168.0.2 *.db.local.
