### ISSUE TITLE
关于log输出问题的一个建议

### ISSUE THREAD

**Issue by wansen** [shawn1m/overture#72]
首先非常感谢你的付出！一直在找android上好用的dns客户端，除dnsmasq和本软件可以很好使用外，其它基本没有什么好用的客户端（也许我没有找到吧）；而dnsmasq已经很久没有更新了，最主要的是如果在android上启动了dnsmasq，则android热点就不能用，这点很是无奈。直到最近，发现你开发的overture，才知道还有这样一个好用的客户端。

因我不是业内人士，提不出什么专业的问题，就本人在使用过程中的一个建议就是：能否增加一个log输出的配置参数，以方便追查使用过程。因为在android上，一般将主程序放到/system/bin文件夹内，配置文件放置在其它地方，在通过sh启动时，要么通过-c启动配置文件，要么通过-l启动log文件，两者有点不能同时启用，所有过来提个issue。

如方便，请采纳，不方便，则忽略。再次感谢你的付出！

**Comment by shawn1m** [comment]
应该可以同时使用的
```
$ /system/bin/overture -c /somewhere/config.json -l /somewhere/overture.log
```

**Comment by wansen** [comment]
谢谢你的回复，我再测试下，如果不行再来回复。

**Comment by wansen** [comment]
因为考虑到要放到后台运行，所用使用nohup启动，不过通过nohup /system/bin/overture-linux-arm -v -c /somewhere/overture.json >/somewhere/overture.log 2>&1 & 达到同样的效果。谢谢你的回复。
