### ISSUE TITLE
同时查询 primary 与 alternative DNS

### ISSUE THREAD

**Issue by tobyxdd** [shawn1m/overture#73]
目前是否查询 alternative DNS 的判断是依赖 primary DNS 的返回结果，因此要得到 alternative DNS 结果实际上总是增加了一个 primary DNS 的延迟。如果对于每个 query 都同时查询 alternative 与 primary，然后只是根据 primary 的结果判断用哪个返回，可以可观地减少延迟改善体验。我的类似项目 anchorDNS 就是这样 (https://github.com/tobyxdd/anchorDNS) 不过不打算维护了 以后我自己也用 overture 了 😉

**Comment by shawn1m** [comment]
曾经实现过二者同时返回结果 2717d168c98fe46c9019fd0e08751de68054ac2f ，但由于考虑到网络开销的问题又将其取消了，毕竟如果 Alternative DNS 是 TCP 上游握手开销还是很大的。未来可以考虑把这个做成可选项。

**Comment by tobyxdd** [comment]
了解了 谢谢

**Comment by easyteacher** [comment]
希望能做成选项

**Comment by Alion548** [comment]
建议能做成选项

**Comment by NyaMisty** [comment]
pr已交，做了个AlernativeDNSConcurrent选项，可以解决问题
顺便握手开销应该通过连接池来避免，而不是单纯的取消这个功能。
如果按次序来查询的话则会像tobyxdd所说一般，会严重的影响查询性能
顺便膜tobyxdd大神
