### ISSUE TITLE
一些特殊域名引发的问题

### ISSUE THREAD

**Issue by wendellou** [shawn1m/overture#85]
国内绝大多数DNS对于：
static.xx.fbcdn.net 
scontent-nrt1-1.xx.fbcdn.net
这样的域名解析，直接采取不应答阻塞的错误，这时候发现不能走AlternativeDNS，结果返回了空值。

**Comment by shawn1m** [comment]
You may turn "DomainBase64Decode" to "false" and use your own DomainFile rule to redirect those queries to AlternativeDNS.

**Comment by wendellou** [comment]
按理说，不是PrimaryDNS不应答，timeout以后，还是会继续请求AlternativeDNS的吗？

**Comment by shawn1m** [comment]
不会，这样超时过长。
