### ISSUE TITLE
overture 对于 `@@` 例外规则在 Base64 编码前后处理不一致

### ISSUE THREAD

**Issue by laggardkernel** [shawn1m/overture#89]
默认配置中，`domain_sample`配置文件实际为base64编码后的gfwlist。自己测试时以`www.qq.com`查询为例（对应文件中例外规则`@@||qq.com`），发现如下问题：
1. base64编码后的`domain_sample`中，`@@`例外规则被忽略，不做使用；
2. 若使用`domain_sample` base64解码后的明文配置文件，尽管存在`@@||qq.com`，`www.qq.com`却走了 alternative DNS。猜测是仅仅忽略了`@@`符号，剩余`||qq.com`部分做了匹配。

以下是使用`domain_sample` **base64解码**配置文件的部分日志。
```
DEBU[0040] Question from 127.0.0.1: ;www.qq.com.	IN	 A
DEBU[0040] Matched: Custom domain www.qq.com qq.com
DEBU[0040] Finally use alternative DNS
```

更新
好像和 #52 部分重复。不过我这边的使用目的并非是要自定义白名单，而是需要自定义黑名单。于是 base64 解码 `domain_sample` 添加了自定义黑名单条目，因为懒得再编码回去修改了配置文件`"DomainBase64Decode": false,`。这样看，只是 overture 对于解码后的域名配置处理失误。

**Comment by shawn1m** [comment]
由 #52 可知，当前base64这种做法只是 workaround，最快下个版本就会被在主程序中删除移入到脚本当中去，#91 初步完成了白名单的功能，你可以自行编译使用，形成版本的话我还要做一些命名上的修改。
