### ISSUE TITLE
EDNS信息长度不正确

### ISSUE THREAD

**Issue by MsShady** [shawn1m/overture#92]
当前只使用overture为DNS查询添加客户端IP到ECS信息，配置如下
```
{
  "BindAddress": ":53",
  "PrimaryDNS": [
    {
      "Name": "Unbound-HZ",
      "Address": "127.0.0.1:2053",
      "Protocol": "udp",
      "SOCKS5Address": "",
      "Timeout": 10,
      "EDNSClientSubnet": {
        "Policy": "auto",
        "ExternalIP": "ExternalIP"
      }
    }
  ],
  "AlternativeDNS": [
    {
      "Name": "Unbound-HK1",
      "Address": "192.168.100.12:2353",
      "Protocol": "udp",
      "SOCKS5Address": "",
      "Timeout": 5,
      "EDNSClientSubnet": {
        "Policy": "disable",
        "ExternalIP": ""
      }
    }
  ],
  "OnlyPrimaryDNS": true,
  "RedirectIPv6Record": false,
  "IPNetworkFile": "",
  "DomainFile": "",
  "DomainBase64Decode": true,
  "HostsFile": "",
  "MinimumTTL": 0,
  "CacheSize" : 0,
  "RejectQtype": [255]
}
```
使用dig查询时可以正常返回结果，但是作为DNS服务器使用则会出现问题。
```
$ dig api.userstyles.org @ExternalIP

; <<>> DiG 9.10.3-P4-Debian <<>> api.userstyles.org @ExternalIP
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25898
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; CLIENT-SUBNET: ClientIP/32/0
;; QUESTION SECTION:
;api.userstyles.org.            IN      A

;; ANSWER SECTION:
api.userstyles.org.     3359    IN      CNAME   apiuserstylesorg-1456121082.us-east-1.elb.amazonaws.com.
apiuserstylesorg-1456121082.us-east-1.elb.amazonaws.com. 60 IN A 52.21.156.1
apiuserstylesorg-1456121082.us-east-1.elb.amazonaws.com. 60 IN A 52.200.177.249

;; Query time: 184 msec
;; SERVER: ExternalIP#53(ExternalIP)
;; WHEN: Sun May 20 12:07:59 DST 2018
;; MSG SIZE  rcvd: 288
```

dig发出的请求抓包：
![wireshark_2018-05-20_15-56-52](https://user-images.githubusercontent.com/39401388/40276848-c24b57cc-5c46-11e8-8d39-77bfac129c6b.png)

Windows发出的查询请求抓包：
![wireshark_2018-05-20_12-15-22](https://user-images.githubusercontent.com/39401388/40275620-9da18eb0-5c27-11e8-8ad8-55b3fa3f67df.png)

**少了Additional Records**

使用dig时 overture向上游Unbound请求的抓包：
![wireshark_2018-05-20_16-05-17](https://user-images.githubusercontent.com/39401388/40276915-25d06606-5c48-11e8-984e-1ce86597a41e.png)

作为DNS服务器时 overture向上游Unbound请求的抓包：
![wireshark_2018-05-20_11-59-39](https://user-images.githubusercontent.com/39401388/40275638-30a3b1d4-5c28-11e8-9cfa-00ac27623724.png)

**似乎是Flag和UDP Payload Size不正确**

**上游Unbound的DEBUG信息中提示** `unbound[4584:0] debug: worker request: edns is too small.`
错误信息在源码中的位置：[unbound/worker.c#L1282](https://github.com/NLnetLabs/unbound/blob/master/daemon/worker.c#L1282)

**Comment by shawn1m** [comment]
auto: If client IP is not in the reserved IP network, use client IP. Otherwise, use external IP.
你使用的 client IP 显然属于保留 IP 所以会使用你所设置的 External IP， 但是你设置的 External IP 是 "ExternalIP" 这无法识别。

**Comment by MsShady** [comment]
linux作为DNS服务器也是同样的问题。
并且现在dig加上+noadflag参数进行查询之后依然正常，此时查询请求的flag和出现问题的查询相同（为0x00000100）。唯一的区别只在于dig比问题请求多了个Additional Records。
推测是overture在处理缺少Additional Records的请求时不正确，向上游的Unbound发出了畸形的查询请求，从而导致了问题。

**Comment by shawn1m** [comment]
恩，看起来应该是需要处理一下 opt 模块的 udpsize 到 4096
```
func (rr *OPT) SetUDPSize(size uint16)
```
等我有空了再调试一下，你可以自己试试。

https://github.com/shawn1m/overture/blob/5c352ceaceaa73275db9a43ad053b758ca118583/core/common/edns.go#L20-L26

**Comment by MsShady** [comment]
加了之后已经可以正常工作了

**Comment by shawn1m** [comment]
Try release v1.4-rc1.
