### ISSUE TITLE
1.3.6.2版本SOCKS5Address有问题

### ISSUE THREAD

**Issue by xixitalk** [shawn1m/overture#96]
1.3.6.2版本配置SOCKS5Address，查询国外域名（如dig  @127.0.0.1  twitter.com）卡死不返回，查询国内域名是好的。
同样的配置1.3.6.1版本就是ok的。

  "AlternativeDNS": [
    {
      "Name": "google",
      "Address": "8.8.8.8:53",
      "Protocol": "tcp",
      "SOCKS5Address": "192.168.1.104:1081",
      "Timeout": 6,
      "EDNSClientSubnet": {
        "Policy": "auto",
        "ExternalIP": "114.221.100.2"
      }
    }
  ],

环境：树莓派 raspbian + overture-linux-arm

**Comment by shawn1m** [comment]
能提供一下 log 信息以及如果可能的抓包信息？

**Comment by patrickwangqy** [comment]
log信息如下
![image](https://user-images.githubusercontent.com/22412010/41856351-6e77f84c-78c7-11e8-8ec4-e397fa6fac2b.png)

**Comment by comzyh** [comment]
类似问题，我查查试试。

**Comment by Yusoo** [comment]
我的也是

**Comment by comzyh** [comment]
@shawn1m 我尝试使用和你一样的travis build了你的[1.3.6.2版本](https://github.com/comzyh/overture/releases/tag/1.3.6.2.5) ，问题消失
估计是你五月build的时候有哪个依赖包有bug，建议直接重新build一个新的，可能就好了、

至于原来的问题，可能无从查证，我这边直接使用你Release版本会出现问题，目前测试这个问题非常好复现，只要用你这个[Release](https://github.com/shawn1m/overture/releases/tag/1.3.6.2)里的binary就可以。

> INFO[0000] If you need any help, please visit the project repository: https://github.com/shawn1m/overture 
> INFO[0000] Load IP network file successful              
> INFO[0000] Load domain file successful                  
> INFO[0000] Minimum TTL is disabled                      
> INFO[0000] Cache is disabled                            
> DEBU[0000] Load hosts took 137ns                        
> INFO[0000] Load hosts file successful                   
> INFO[0000] Start overture on :5354                      
> DEBU[0002] Question from 127.0.0.1: ;google.com.	IN	 A  
> DEBU[0002] Matched: Custom domain google.com google.com 
> DEBU[0002] Finally use alternative DNS                  
> DEBU[0003] cloudflare Fail: Response message is nil, maybe timeout, please check your query or dns configuration 
> DEBU[0007] Question from 127.0.0.1: ;google.com.	IN	 A  
> DEBU[0007] Matched: Custom domain google.com google.com 
> DEBU[0007] Finally use alternative DNS                  
> DEBU[0008] cloudflare Fail: Response message is nil, maybe timeout, please check your query or dns configuration 

我认为你在 https://github.com/shawn1m/overture/blob/5875f095c399943dbefc27a84c1068b34627dd4d/core/outbound/client.go#L90-L95
这个段代码判断`err != nil` 之后没有判断其他Error，这时可能有其他err，但是

https://github.com/shawn1m/overture/blob/5875f095c399943dbefc27a84c1068b34627dd4d/core/outbound/client.go#L97

造成我们只能看到空响应错误

@Yusoo @patrickwangqy  可以自己build一份，或者用我刚build的，应该能解决https://github.com/comzyh/overture/releases/tag/1.3.6.2.5

**Comment by shawn1m** [comment]
@comzyh 这么看很有可能是依赖包问题，感谢你精彩的分析。周末有空的话可能会发一个新版本，overture 需要进行一定的优化配置与重构。
